// ::: Code Generated by Copilot [f7a1d9e0-2c3b-48f5-a6e1-7d4b8c5f9a02]. This comment will be removed automatically after the file is saved :::
import React, { useEffect, useState, useCallback } from "react";
import {
  ActivityIndicator,
  Alert,
  Platform,
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { launchCamera, launchImageLibrary } from "react-native-image-picker";
import { DataLift, isDataLiftAvailable } from "react-native-datalift";
import type { DataLiftResponse } from "react-native-datalift";

// ─── Helpers ──────────────────────────────────────────────────────────────────

const JsonField = ({ label, value }: { label: string; value: unknown }) => {
  const display =
    value === undefined || value === null || value === ""
      ? "—"
      : typeof value === "object"
        ? JSON.stringify(value)
        : String(value);

  return (
    <View style={styles.jsonRow}>
      <Text style={styles.jsonKey}>{label}</Text>
      <Text style={styles.jsonValue} numberOfLines={2}>
        {display}
      </Text>
    </View>
  );
};

// ::: Code Generated by Copilot [f7a1d9e0-2c3b-48f5-a6e1-7d4b8c5f9a02]. This comment will be removed automatically after the file is saved :::
const ResultTile = ({ result }: { result: DataLiftResponse }) => {
  const docType = String(
    result.metadata?.documentType ?? "generic",
  ).toUpperCase();
  const confidence = `${Math.round((result.metadata?.confidenceScore ?? 0) * 100)}%`;
  const total = result.totals?.grandTotal ?? "not found";
  const invoiceNo = result.transaction?.invoiceNumber ?? "not found";
  const lineItems = result.parts?.length ?? 0;
  const aiProvider = result.metadata?.aiProviderUsed ?? "none";
  const warnings = result.metadata?.warnings ?? [];

  return (
    <View style={styles.resultCard}>
      <View style={styles.resultTopRow}>
        <Text style={styles.resultType}>{docType}</Text>
        <Text style={styles.badge}>{confidence}</Text>
      </View>
      <Text style={styles.resultMeta}>Invoice/Receipt No: {invoiceNo}</Text>
      <Text style={styles.resultMeta}>
        Vendor: {result.supplier?.name ?? "—"}
      </Text>
      <Text style={styles.resultMeta}>Line items: {lineItems}</Text>
      <Text style={styles.resultMeta}>Total: {total}</Text>
      <Text style={styles.resultMeta}>AI/Model: {aiProvider}</Text>
      {warnings.length > 0 && (
        <Text style={styles.warningSmall}>
          {warnings.length} warning(s): {warnings[0]}
        </Text>
      )}
      <Text style={styles.rawLabel}>JSON preview</Text>
      <Text style={styles.rawPreview} numberOfLines={10}>
        {JSON.stringify(result, null, 2)}
      </Text>
    </View>
  );
};

// ─── Main App ─────────────────────────────────────────────────────────────────

// ::: Code Generated by Copilot [f7a1d9e0-2c3b-48f5-a6e1-7d4b8c5f9a02]. This comment will be removed automatically after the file is saved :::
const App = () => {
  // LayoutLMv3 model paths — bare filenames resolved from app bundle by native
  const layoutLMv3ModelPath = "layoutlmv3_invoice.onnx";
  const layoutLMv3LabelsPath = "layoutlmv3_labels.txt";

  const [results, setResults] = useState<DataLiftResponse[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [modelStatus, setModelStatus] = useState<string>("configuring…");

  // ─── Configure LayoutLMv3 on mount (non-blocking) ──────────────────────
  // DataLift.extract() always works (OCR + rule-based parser).
  // If the model is also configured, step 5.5 runs LayoutLMv3 automatically.

  useEffect(() => {
    let active = true;

    const configureModel = async () => {
      try {
        const configResult = await DataLift.configureLayoutLMv3({
          modelPath: layoutLMv3ModelPath,
          labelsPath: layoutLMv3LabelsPath,
        });

        const compat = await DataLift.checkLayoutLMv3Compatibility({
          modelPath: layoutLMv3ModelPath,
          labelsPath: layoutLMv3LabelsPath,
        });

        if (!active) return;

        if (compat.compatible) {
          setModelStatus("ready (all 3 stages active)");
        } else {
          setModelStatus(
            `OCR + parser only — model: ${compat.error ?? "incompatible"}`,
          );
        }
      } catch (err) {
        if (!active) return;
        const msg = err instanceof Error ? err.message : String(err);
        setModelStatus(`OCR + parser only — ${msg}`);
      }
    };

    configureModel();
    return () => {
      active = false;
    };
  }, [layoutLMv3ModelPath, layoutLMv3LabelsPath]);

  // ─── Unified extraction — OCR → Parser → LayoutLMv3 (if configured) ────

  const processUri = useCallback(
    async (uri: string) => {
      setLoading(true);
      setError(null);
      try {
        // All 3 stages run inside DataLift.extract():
        //  1. OCR (Apple Vision / ML Kit)
        //  2. RuleBasedParser
        //  3. LayoutLMv3 native prediction (step 5.5, auto when configured)
        const result = await DataLift.extract({
          image: uri,
          language: "eng",
          debug: __DEV__,
          // Pass model paths — extract() uses them for step 5.5 LayoutLMv3
          layoutLMv3ModelPath,
          layoutLMv3LabelsPath,
        });
        setResults((prev) => [result, ...prev]);
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        setError(msg);
        Alert.alert("Extraction Error", msg);
      } finally {
        setLoading(false);
      }
    },
    [layoutLMv3ModelPath, layoutLMv3LabelsPath],
  );

  // ─── Camera capture ────────────────────────────────────────────────────

  const handleCapture = useCallback(async () => {
    launchCamera(
      { mediaType: "photo", cameraType: "back", quality: 1 },
      async (response) => {
        if (response.didCancel) return;
        if (response.errorCode) {
          Alert.alert(
            "Camera Error",
            response.errorMessage ?? response.errorCode,
          );
          return;
        }
        const uri = response.assets?.[0]?.uri;
        if (uri) await processUri(uri);
      },
    );
  }, [processUri]);

  // ─── Gallery pick ──────────────────────────────────────────────────────

  const handlePick = useCallback(async () => {
    launchImageLibrary(
      { mediaType: "photo", selectionLimit: 5 },
      async (response) => {
        if (response.didCancel) return;
        if (response.errorCode) {
          Alert.alert(
            "Gallery Error",
            response.errorMessage ?? response.errorCode,
          );
          return;
        }
        const uris = (response.assets ?? [])
          .map((a) => a.uri)
          .filter((u): u is string => !!u);
        for (const uri of uris) {
          await processUri(uri);
        }
      },
    );
  }, [processUri]);

  // ─── Utility ────────────────────────────────────────────────────────────

  const printLatestJsonToConsole = () => {
    if (results.length === 0) {
      Alert.alert("No Results", "Capture or pick an image first.");
      return;
    }
    console.log(
      "[DataLift][LatestResult]",
      JSON.stringify(results[0], null, 2),
    );
    Alert.alert("Printed", "Latest JSON printed in Metro console.");
  };

  const clearResults = () => {
    setResults([]);
    setError(null);
  };

  // ─── Render ─────────────────────────────────────────────────────────────

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="dark-content" backgroundColor="#f8fafc" />
      <ScrollView contentContainerStyle={styles.content}>
        <View style={styles.hero}>
          <Text style={styles.title}>DataLift Example</Text>
          <Text style={styles.subtitle}>
            Unified 3-stage pipeline: OCR → Rule-Based Parser → LayoutLMv3
          </Text>
        </View>

        {!isDataLiftAvailable && (
          <View style={styles.warning}>
            <Text style={styles.warningText}>
              Native module not linked.{" "}
              {Platform.OS === "ios"
                ? "Run pod install + rebuild."
                : "Run a clean Android build."}
            </Text>
          </View>
        )}

        <View style={styles.card}>
          <Text style={styles.sectionTitle}>Document Extraction</Text>
          <Text style={styles.sectionText}>
            DataLift.extract() runs all 3 stages automatically:{"\n"}
            1. Native OCR (Apple Vision / ML Kit){"\n"}
            2. Rule-based parser (invoice/receipt fields){"\n"}
            3. LayoutLMv3 on-device prediction (fills gaps)
          </Text>

          <View style={styles.statusRow}>
            <View
              style={[
                styles.statusDot,
                modelStatus.startsWith("ready")
                  ? styles.statusGreen
                  : styles.statusOrange,
              ]}
            />
            <Text style={styles.statusText}>{modelStatus}</Text>
          </View>

          <View style={styles.buttonRow}>
            <TouchableOpacity
              style={[styles.button, loading && styles.buttonDisabled]}
              disabled={loading}
              onPress={handleCapture}
            >
              <Text style={styles.buttonText}>Capture</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[
                styles.button,
                styles.buttonSecondary,
                loading && styles.buttonDisabled,
              ]}
              disabled={loading}
              onPress={handlePick}
            >
              <Text style={styles.buttonText}>Pick Images</Text>
            </TouchableOpacity>
          </View>

          {loading && (
            <View style={styles.loadingBox}>
              <ActivityIndicator color="#0ea5e9" />
              <Text style={styles.loadingText}>Processing (3 stages)…</Text>
            </View>
          )}

          {!!error && <Text style={styles.errorText}>{error}</Text>}
        </View>

        <View style={styles.resultsHeader}>
          <Text style={styles.resultsTitle}>Results ({results.length})</Text>
          <View style={styles.resultsActions}>
            <TouchableOpacity
              onPress={printLatestJsonToConsole}
              style={styles.consoleBtn}
            >
              <Text style={styles.consoleBtnText}>JSON Console</Text>
            </TouchableOpacity>
            <TouchableOpacity onPress={clearResults} style={styles.clearBtn}>
              <Text style={styles.clearBtnText}>Clear</Text>
            </TouchableOpacity>
          </View>
        </View>

        {results.length === 0 ? (
          <View style={styles.emptyState}>
            <Text style={styles.emptyTitle}>No output yet</Text>
            <Text style={styles.emptyText}>
              Capture or pick an image to run the unified extraction pipeline.
            </Text>
          </View>
        ) : (
          results.map((result, index) => (
            <ResultTile
              key={`${result.metadata?.processingTimeMs}-${index}`}
              result={result}
            />
          ))
        )}
      </ScrollView>
    </SafeAreaView>
  );
};

// ::: Code Generated by Copilot [f7a1d9e0-2c3b-48f5-a6e1-7d4b8c5f9a02]. This comment will be removed automatically after the file is saved :::
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8fafc" },
  content: { padding: 16, paddingBottom: 28, gap: 12 },
  hero: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 16,
  },
  title: { fontSize: 24, fontWeight: "800", color: "#0f172a" },
  subtitle: { marginTop: 4, color: "#475569", fontSize: 13, lineHeight: 18 },
  warning: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#fde68a",
    backgroundColor: "#fffbeb",
    padding: 12,
  },
  warningText: { color: "#92400e", fontSize: 12, fontWeight: "600" },
  warningSmall: { color: "#d97706", fontSize: 11 },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 14,
    gap: 10,
  },
  sectionTitle: { fontSize: 15, fontWeight: "800", color: "#0f172a" },
  sectionText: { fontSize: 13, color: "#475569", lineHeight: 18 },
  statusRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  statusGreen: { backgroundColor: "#22c55e" },
  statusOrange: { backgroundColor: "#f59e0b" },
  statusText: { color: "#334155", fontSize: 12, fontWeight: "600", flex: 1 },
  buttonRow: { flexDirection: "row", gap: 10 },
  button: {
    flex: 1,
    backgroundColor: "#2563eb",
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  buttonSecondary: { backgroundColor: "#0f766e" },
  buttonDisabled: { opacity: 0.5 },
  buttonText: { color: "#ffffff", fontWeight: "700", fontSize: 13 },
  loadingBox: { flexDirection: "row", alignItems: "center", gap: 8 },
  loadingText: { color: "#334155", fontSize: 12, fontWeight: "600" },
  errorText: { color: "#be123c", fontSize: 12, fontWeight: "600" },
  jsonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  jsonKey: { color: "#475569", fontSize: 12, fontWeight: "700", flex: 1 },
  jsonValue: { color: "#0f172a", fontSize: 12, flex: 1.2, textAlign: "right" },
  resultsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 2,
  },
  resultsActions: { flexDirection: "row", gap: 8 },
  resultsTitle: { fontSize: 16, fontWeight: "800", color: "#0f172a" },
  clearBtn: {
    backgroundColor: "#e2e8f0",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  clearBtnText: { color: "#334155", fontWeight: "700", fontSize: 12 },
  consoleBtn: {
    backgroundColor: "#0f766e",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  consoleBtnText: { color: "#ffffff", fontWeight: "700", fontSize: 12 },
  emptyState: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 16,
    alignItems: "center",
  },
  emptyTitle: { fontWeight: "800", color: "#0f172a", marginBottom: 4 },
  emptyText: { color: "#64748b", fontSize: 12 },
  resultCard: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 12,
    gap: 6,
  },
  resultTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  resultType: { fontWeight: "800", color: "#0f172a", fontSize: 14 },
  badge: {
    backgroundColor: "#ecfeff",
    borderWidth: 1,
    borderColor: "#a5f3fc",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 3,
    color: "#0e7490",
    fontWeight: "800",
    fontSize: 11,
  },
  resultMeta: { color: "#334155", fontSize: 12 },
  rawLabel: { marginTop: 2, color: "#0f172a", fontSize: 12, fontWeight: "700" },
  rawPreview: {
    backgroundColor: "#f8fafc",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 8,
    color: "#334155",
    fontSize: 11,
    lineHeight: 16,
  },
});

export default App;
