// ::: Code Generated by Copilot a1b2c3d4-e5f6-7890-abcd-ef1234567890. This comment will be removed automatically after the file is saved :::
import React, { useEffect, useState, useCallback } from "react";
import {
  ActivityIndicator,
  Alert,
  Button,
  Platform,
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { launchCamera, launchImageLibrary } from "react-native-image-picker";
import { DataLift, isDataLiftAvailable } from "react-native-datalift";
import type { DataLiftResponse } from "react-native-datalift";
import Toast from "components/Toast";

// ─── Helpers ──────────────────────────────────────────────────────────────────

const JsonField = ({ label, value }: { label: string; value: unknown }) => {
  const display =
    value === undefined || value === null || value === ""
      ? "—"
      : typeof value === "object"
        ? JSON.stringify(value)
        : String(value);
  const isEmpty = display === "—";
  if (isEmpty) return null; // hide empty rows to reduce clutter
  return (
    <View style={styles.jsonRow}>
      <Text style={styles.jsonKey}>{label}</Text>
      <Text style={styles.jsonValue} numberOfLines={3} selectable>
        {display}
      </Text>
    </View>
  );
};

const ConfBar = ({ label, value }: { label: string; value: number }) => {
  const pct = Math.round(value * 100);
  const color = pct >= 80 ? "#22c55e" : pct >= 55 ? "#f59e0b" : "#ef4444";
  return (
    <View style={styles.confRow}>
      <Text style={styles.confLabel}>{label}</Text>
      <View style={styles.confTrack}>
        <View
          style={[
            styles.confFill,
            { width: `${pct}%`, backgroundColor: color },
          ]}
        />
      </View>
      <Text style={[styles.confPct, { color }]}>{pct}%</Text>
    </View>
  );
};

const ResultTile = ({
  result,
  index,
}: {
  result: DataLiftResponse;
  index: number;
}) => {
  const [showRaw, setShowRaw] = useState(false);
  const [showOcr, setShowOcr] = useState(false);
  const [showJson, setShowJson] = useState(false);
  const [showAllItems, setShowAllItems] = useState(false);

  const docType = String(
    result.metadata?.documentType ?? "generic",
  ).toUpperCase();
  const confidence = Math.round((result.metadata?.confidenceScore ?? 0) * 100);
  const confColor =
    confidence >= 80 ? "#15803d" : confidence >= 55 ? "#92400e" : "#be123c";
  const confBg =
    confidence >= 80 ? "#f0fdf4" : confidence >= 55 ? "#fffbeb" : "#fff1f2";
  const currency =
    result.transaction?.currency ?? result.totals?.currency ?? "";
  const lineItems = result.parts?.length ?? 0;
  const aiProvider = result.metadata?.aiProviderUsed ?? "none";
  const layoutLMUsed = aiProvider.includes("layoutlmv3");
  const processingMs = result.metadata?.processingTimeMs;
  const cb = result.metadata?.confidenceBreakdown;
  const warnings = result.metadata?.warnings ?? [];
  const rawText: string | undefined = (result as any).rawText;

  const fmt = (v: number | undefined | null, cur = currency) =>
    v != null ? `${v}${cur ? " " + cur : ""}` : undefined;

  return (
    <View style={styles.resultCard}>
      {/* ── Header ── */}
      <View style={styles.resultTopRow}>
        <View style={{ flex: 1 }}>
          <Text style={styles.resultType}>
            #{index + 1} · {docType}
          </Text>
          {processingMs != null && (
            <Text style={styles.timingText}>{processingMs}ms</Text>
          )}
        </View>
        <View style={styles.badgeRow}>
          <View
            style={[
              styles.confBadge,
              { backgroundColor: confBg, borderColor: confColor + "55" },
            ]}
          >
            <Text style={[styles.confBadgeText, { color: confColor }]}>
              {confidence}%
            </Text>
          </View>
          {currency ? (
            <View style={styles.currencyBadge}>
              <Text style={styles.currencyBadgeText}>{currency}</Text>
            </View>
          ) : null}
          {layoutLMUsed && (
            <View style={styles.modelBadge}>
              <Text style={styles.modelBadgeText}>AI</Text>
            </View>
          )}
        </View>
      </View>

      {/* ── Confidence bars ── */}
      {cb && (
        <View style={styles.confSection}>
          <ConfBar label="OCR" value={cb.ocr} />
          <ConfBar label="Fields" value={cb.fields} />
          <ConfBar label="Numeric" value={cb.numeric} />
          <ConfBar label="DocType" value={cb.docType} />
          <ConfBar label="Keywords" value={cb.keyword} />
        </View>
      )}

      {/* ── Supplier ── */}
      <Text style={styles.subSectionLabel}>Supplier</Text>
      <JsonField label="Name" value={result.supplier?.name} />
      <JsonField label="Phone" value={result.supplier?.contact?.phone} />
      <JsonField label="Email" value={result.supplier?.contact?.email} />
      <JsonField label="Website" value={result.supplier?.contact?.website} />
      <JsonField
        label="Tax ID"
        value={result.supplier?.taxInformation?.taxId}
      />
      <JsonField
        label="GST #"
        value={result.supplier?.taxInformation?.gstNumber}
      />
      <JsonField
        label="ABN"
        value={result.supplier?.taxInformation?.abnNumber}
      />
      <JsonField
        label="Address"
        value={result.supplier?.address?.fullAddress}
      />

      {/* ── Buyer ── */}
      {(result.buyer?.name || result.buyer?.address?.fullAddress) && (
        <>
          <Text style={styles.subSectionLabel}>Buyer / Bill-To</Text>
          <JsonField label="Name" value={result.buyer?.name} />
          <JsonField
            label="Address"
            value={result.buyer?.address?.fullAddress}
          />
          <JsonField label="Phone" value={result.buyer?.contact?.phone} />
        </>
      )}

      {/* ── Transaction ── */}
      <Text style={styles.subSectionLabel}>Transaction</Text>
      <JsonField label="Invoice #" value={result.transaction?.invoiceNumber} />
      <JsonField label="PO #" value={result.transaction?.purchaseOrderNumber} />
      <JsonField
        label="Work Order"
        value={result.transaction?.workOrderNumber}
      />
      <JsonField label="Quote #" value={result.transaction?.quoteNumber} />
      <JsonField
        label="Reference"
        value={result.transaction?.referenceNumber}
      />
      <JsonField
        label="Date"
        value={
          result.transaction?.invoiceDate ?? result.transaction?.transactionDate
        }
      />
      <JsonField label="Due Date" value={result.transaction?.dueDate} />
      <JsonField label="Terms" value={result.transaction?.paymentTerms} />
      <JsonField label="Payment Mode" value={result.transaction?.paymentMode} />

      {/* ── Totals ── */}
      <Text style={styles.subSectionLabel}>Totals</Text>
      <JsonField label="Subtotal" value={fmt(result.totals?.subtotal)} />
      <JsonField label="Tax" value={fmt(result.totals?.totalTax)} />
      <JsonField label="Shipping" value={fmt(result.totals?.shippingCost)} />
      <JsonField label="Discount" value={fmt(result.totals?.discount)} />
      <JsonField label="Tip" value={fmt(result.totals?.tip)} />
      <JsonField
        label="Service Charge"
        value={fmt(result.totals?.serviceCharge)}
      />
      <JsonField label="Amount Paid" value={fmt(result.totals?.amountPaid)} />
      <JsonField label="Balance Due" value={fmt(result.totals?.balanceDue)} />
      <JsonField label="Grand Total" value={fmt(result.totals?.grandTotal)} />

      {/* ── Payment details ── */}
      {result.paymentDetails && (
        <>
          <Text style={styles.subSectionLabel}>Payment</Text>
          <JsonField label="Method" value={result.paymentDetails.method} />
          <JsonField
            label="Reference"
            value={result.paymentDetails.reference}
          />
          <JsonField
            label="Receipt #"
            value={result.paymentDetails.receiptNumber}
          />
          {result.paymentDetails.cardType && (
            <JsonField
              label="Card"
              value={`${result.paymentDetails.cardType} ****${result.paymentDetails.cardLast4 ?? ""}`}
            />
          )}
        </>
      )}

      {/* ── Delivery ── */}
      {result.deliveryDetails && (
        <>
          <Text style={styles.subSectionLabel}>Delivery</Text>
          <JsonField
            label="Address"
            value={
              result.deliveryDetails.address?.fullAddress ??
              ([
                result.deliveryDetails.address?.street,
                result.deliveryDetails.address?.city,
                result.deliveryDetails.address?.state,
                result.deliveryDetails.address?.postalCode,
              ]
                .filter(Boolean)
                .join(", ") ||
                undefined)
            }
          />
          <JsonField label="Date" value={result.deliveryDetails.date} />
          <JsonField
            label="Tracking"
            value={result.deliveryDetails.trackingNumber}
          />
          <JsonField label="Carrier" value={result.deliveryDetails.carrier} />
        </>
      )}

      {/* ── Notes ── */}
      {!!result.notes && (
        <>
          <Text style={styles.subSectionLabel}>Notes</Text>
          <Text style={styles.notesText} selectable>
            {result.notes}
          </Text>
        </>
      )}

      {/* ── Line items ── */}
      {lineItems > 0 && (
        <>
          <Text style={styles.subSectionLabel}>Line Items ({lineItems})</Text>
          {(showAllItems ? result.parts : result.parts.slice(0, 8)).map(
            (part, i) => (
              <View key={i} style={styles.lineItemRow}>
                <Text style={styles.lineItemName} numberOfLines={2}>
                  {part.itemName}
                  {part.sku ? ` [${part.sku}]` : ""}
                  {part.description ? `\n${part.description}` : ""}
                </Text>
                <Text style={styles.lineItemAmt}>
                  {part.quantity ?? "?"}
                  {part.unit ? " " + part.unit : ""} × {part.unitPrice ?? "?"} ={" "}
                  {part.totalAmount ?? "?"}
                  {currency ? " " + currency : ""}
                </Text>
              </View>
            ),
          )}
          {lineItems > 8 && (
            <TouchableOpacity
              onPress={() => setShowAllItems((v) => !v)}
              style={styles.toggleBtn}
            >
              <Text style={styles.toggleBtnText}>
                {showAllItems
                  ? "▲ Show fewer"
                  : `▼ Show all ${lineItems} items`}
              </Text>
            </TouchableOpacity>
          )}
        </>
      )}

      {/* ── Warnings ── */}
      {warnings.length > 0 && (
        <View style={styles.warningBox}>
          {warnings.map((w, i) => (
            <Text key={i} style={styles.warningSmall}>
              ⚠ {w}
            </Text>
          ))}
        </View>
      )}

      {/* ── Stage info ── */}
      <View style={styles.stageRow}>
        <Text style={styles.stageMeta}>
          OCR: {result.metadata?.ocrProvider ?? "—"} · Fields:{" "}
          {result.metadata?.fieldCount ?? 0}
        </Text>
        <Text style={[styles.stageMeta, layoutLMUsed && styles.stageMetaAI]}>
          {layoutLMUsed ? `✓ LayoutLMv3` : "LayoutLMv3: skip"}
        </Text>
      </View>

      {/* ── OCR raw text toggle ── */}
      {rawText && (
        <TouchableOpacity
          onPress={() => setShowOcr((v) => !v)}
          style={styles.toggleBtn}
        >
          <Text style={styles.toggleBtnText}>
            {showOcr ? "▲ Hide" : "▼ Show"} OCR text
          </Text>
        </TouchableOpacity>
      )}
      {showOcr && rawText && (
        <ScrollView style={styles.rawBox} nestedScrollEnabled>
          <Text style={styles.rawText} selectable>
            {rawText}
          </Text>
        </ScrollView>
      )}

      {/* ── JSON preview toggle ── */}
      <TouchableOpacity
        onPress={() => setShowJson((v) => !v)}
        style={styles.toggleBtn}
      >
        <Text style={styles.toggleBtnText}>
          {showJson ? "▲ Hide" : "▼ Show"} JSON
        </Text>
      </TouchableOpacity>
      {showJson && (
        <ScrollView style={styles.rawBox} nestedScrollEnabled>
          <Text style={styles.rawText} selectable>
            {JSON.stringify(result, null, 2)}
          </Text>
        </ScrollView>
      )}
    </View>
  );
};

// ─── Main App ─────────────────────────────────────────────────────────────────

// ::: Code Generated by Copilot a1b2c3d4-e5f6-7890-abcd-ef1234567890. This comment will be removed automatically after the file is saved :::
const App = () => {
  const [results, setResults] = useState<DataLiftResponse[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  // ::: Code Generated by Copilot 9e1f2a3b-4c5d-6e7f-8091-a2b3c4d5e6f7. This comment will be removed automatically after the file is saved :::
  const [modelStatus, setModelStatus] = useState<string>("loading model…");

  useEffect(() => {
    let active = true;

    // Fine-tuned LayoutLMv3 model lifecycle:
    //   Android: layoutlmv3-base-doc-android.onnx is bundled in APK assets — no download needed.
    //   iOS:     CoreML model (~221 MB) is NOT bundled; autoDownload: true fetches it once from
    //            GitHub Release "models-v1" and caches it on device.
    DataLift.configure({
      // Allow iOS to download the CoreML model on first run; Android uses bundled ONNX.
      autoDownloadLayoutLMv3: Platform.OS !== "android",
      // Enable verbose logging in debug builds to aid accuracy diagnosis.
      debug: __DEV__,
    });

    (async () => {
      try {
        // prepareModel() resolution order:
        //   1. Bundled assets (Android: APK assets; iOS: Bundle.main resources)
        //   2. Previously extracted/downloaded model in device storage
        //   3. Remote download — only on iOS where the CoreML model is not bundled
        const result = await DataLift.prepareModel({
          autoDownload: Platform.OS !== "android",
        });
        if (!active) return;
        if (result.ready) {
          setModelStatus(
            `✓ ready (${result.source ?? "bundle"}) — OCR → Parser → LayoutLMv3 → AI`,
          );
        } else {
          // Model not available — will run OCR + Parser + AI (stage 5) only
          setModelStatus("✓ ready — OCR → Parser → AI (no LayoutLMv3)");
        }
      } catch (err) {
        if (!active) return;
        const msg = err instanceof Error ? err.message : String(err);
        setModelStatus(`OCR + parser only — ${msg}`);
      }
    })();

    return () => {
      active = false;
    };
  }, []);

  const processUri = useCallback(async (uri: string) => {
    setLoading(true);
    setError(null);
    try {
      const result = await DataLift.extract({
        imageInput: { type: "uri", path: uri },
        // Omit `language` to let the SDK auto-detect from document content.
        // Hardcoding "en" breaks extraction for non-English documents.
        extractRawText: true, // capture OCR output for accuracy inspection
        debug: __DEV__,
      });
      setResults((prev) => [result, ...prev]);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      setError(msg);
      Alert.alert("Extraction Error", msg);
    } finally {
      setLoading(false);
    }
  }, []);

  const handleCapture = useCallback(() => {
    launchCamera(
      { mediaType: "photo", cameraType: "back", quality: 1 },
      async (response) => {
        if (response.didCancel) return;
        if (response.errorCode) {
          Alert.alert(
            "Camera Error",
            response.errorMessage ?? response.errorCode,
          );
          return;
        }
        const uri = response.assets?.[0]?.uri;
        if (uri) await processUri(uri);
      },
    );
  }, [processUri]);

  const handlePick = useCallback(() => {
    launchImageLibrary(
      { mediaType: "photo", selectionLimit: 5 },
      async (response) => {
        if (response.didCancel) return;
        if (response.errorCode) {
          Alert.alert(
            "Gallery Error",
            response.errorMessage ?? response.errorCode,
          );
          return;
        }
        const uris = (response.assets ?? [])
          .map((a) => a.uri)
          .filter((u): u is string => !!u);
        for (const uri of uris) {
          await processUri(uri);
        }
      },
    );
  }, [processUri]);

  const printLatest = () => {
    if (results.length === 0) {
      Alert.alert("No Results", "Capture or pick an image first.");
      return;
    }
    console.log("[DataLift][Latest]", JSON.stringify(results[0], null, 2));
    Alert.alert("Printed", "Latest JSON printed in Metro console.");
  };

  let isToastVisible = false;

  const onButtonClick = () => {
    isToastVisible = true;
  };

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="dark-content" backgroundColor="#f8fafc" />
      <ScrollView contentContainerStyle={styles.content}>
        <View style={styles.hero}>
          <Text style={styles.title}>DataLift v1.3.0</Text>
          <Text style={styles.subtitle}>
            OCR → Rule parser → Confidence → LayoutLMv3 → AI fallback
          </Text>
        </View>

        {!isDataLiftAvailable && (
          <View style={styles.warningCard}>
            <Text style={styles.warningCardText}>
              Native module not linked.{" "}
              {Platform.OS === "ios"
                ? "Run pod install + rebuild."
                : "Clean Android build required."}
            </Text>
          </View>
        )}

        <View style={styles.card}>
          <View style={styles.statusRow}>
            <View
              style={[
                styles.statusDot,
                modelStatus.startsWith("✓")
                  ? styles.statusGreen
                  : styles.statusOrange,
              ]}
            />
            <Text style={styles.statusText} numberOfLines={2}>
              {modelStatus}
            </Text>
            <Button title="Call" onPress={() => onButtonClick} />

            {isToastVisible && <Toast message={"Called at button Click"} />}
          </View>

          <View style={styles.buttonRow}>
            <TouchableOpacity
              style={[styles.button, loading && styles.buttonDisabled]}
              disabled={loading}
              onPress={handleCapture}
            >
              <Text style={styles.buttonText}>📷 Capture</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[
                styles.button,
                styles.buttonSecondary,
                loading && styles.buttonDisabled,
              ]}
              disabled={loading}
              onPress={handlePick}
            >
              <Text style={styles.buttonText}>🖼 Gallery</Text>
            </TouchableOpacity>
          </View>

          {loading && (
            <View style={styles.loadingBox}>
              <ActivityIndicator color="#0ea5e9" />
              <Text style={styles.loadingText}>
                Running extraction pipeline…
              </Text>
            </View>
          )}

          {!!error && <Text style={styles.errorText}>{error}</Text>}
        </View>

        <View style={styles.resultsHeader}>
          <Text style={styles.resultsTitle}>Results ({results.length})</Text>
          <View style={styles.resultsActions}>
            {results.length > 0 && (
              <TouchableOpacity onPress={printLatest} style={styles.consoleBtn}>
                <Text style={styles.consoleBtnText}>Console</Text>
              </TouchableOpacity>
            )}
            {results.length > 0 && (
              <TouchableOpacity
                onPress={() => {
                  setResults([]);
                  setError(null);
                }}
                style={styles.clearBtn}
              >
                <Text style={styles.clearBtnText}>Clear</Text>
              </TouchableOpacity>
            )}
          </View>
        </View>

        {results.length === 0 ? (
          <View style={styles.emptyState}>
            <Text style={styles.emptyTitle}>No results yet</Text>
            <Text style={styles.emptyText}>
              Capture or pick a document to run all pipeline stages.{"\n"}
              For best accuracy: clear background, good lighting, keep flat.
            </Text>
          </View>
        ) : (
          results.map((result, index) => (
            <ResultTile key={index} result={result} index={index} />
          ))
        )}
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8fafc" },
  content: { padding: 14, paddingBottom: 32, gap: 12 },

  hero: {
    backgroundColor: "#0f172a",
    borderRadius: 14,
    padding: 16,
  },
  title: { fontSize: 22, fontWeight: "800", color: "#f1f5f9" },
  subtitle: { marginTop: 4, color: "#94a3b8", fontSize: 12, lineHeight: 18 },

  warningCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#fde68a",
    backgroundColor: "#fffbeb",
    padding: 12,
  },
  warningCardText: { color: "#92400e", fontSize: 12, fontWeight: "600" },

  card: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 14,
    gap: 10,
  },

  // Status row
  statusRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  statusGreen: { backgroundColor: "#22c55e" },
  statusOrange: { backgroundColor: "#f59e0b" },
  statusText: { color: "#334155", fontSize: 12, fontWeight: "600", flex: 1 },

  // Buttons
  buttonRow: { flexDirection: "row", gap: 10 },
  button: {
    flex: 1,
    backgroundColor: "#2563eb",
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: "center",
  },
  buttonSecondary: { backgroundColor: "#0f766e" },
  buttonDisabled: { opacity: 0.4 },
  buttonText: { color: "#ffffff", fontWeight: "700", fontSize: 13 },

  // Loading / error
  loadingBox: { flexDirection: "row", alignItems: "center", gap: 8 },
  loadingText: { color: "#334155", fontSize: 12, fontWeight: "600" },
  errorText: { color: "#be123c", fontSize: 12, fontWeight: "600" },

  // Results header
  resultsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 2,
  },
  resultsActions: { flexDirection: "row", gap: 8 },
  resultsTitle: { fontSize: 16, fontWeight: "800", color: "#0f172a" },
  clearBtn: {
    backgroundColor: "#e2e8f0",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  clearBtnText: { color: "#334155", fontWeight: "700", fontSize: 12 },
  consoleBtn: {
    backgroundColor: "#0f766e",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  consoleBtnText: { color: "#ffffff", fontWeight: "700", fontSize: 12 },

  // Empty state
  emptyState: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 20,
    alignItems: "center",
    gap: 6,
  },
  emptyTitle: { fontWeight: "800", color: "#0f172a", fontSize: 14 },
  emptyText: {
    color: "#64748b",
    fontSize: 12,
    textAlign: "center",
    lineHeight: 18,
  },

  // Result card
  resultCard: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 12,
    gap: 5,
  },
  resultTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  resultType: { fontWeight: "800", color: "#0f172a", fontSize: 14 },
  timingText: { color: "#94a3b8", fontSize: 10, marginTop: 1 },
  badgeRow: {
    flexDirection: "row",
    gap: 4,
    alignItems: "center",
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  confBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  confBadgeText: { fontWeight: "800", fontSize: 11 },
  currencyBadge: {
    backgroundColor: "#f0fdf4",
    borderWidth: 1,
    borderColor: "#86efac",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  currencyBadgeText: { color: "#15803d", fontWeight: "700", fontSize: 10 },
  modelBadge: {
    backgroundColor: "#eef2ff",
    borderWidth: 1,
    borderColor: "#a5b4fc",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  modelBadgeText: { color: "#4338ca", fontWeight: "800", fontSize: 10 },

  // Confidence bars
  confSection: { gap: 3, marginVertical: 4 },
  confRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  confLabel: { color: "#64748b", fontSize: 10, fontWeight: "600", width: 48 },
  confTrack: {
    flex: 1,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#e2e8f0",
    overflow: "hidden",
  },
  confFill: { height: 5, borderRadius: 3 },
  confPct: { fontSize: 10, fontWeight: "700", width: 32, textAlign: "right" },

  // JSON field rows
  jsonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  jsonKey: { color: "#475569", fontSize: 12, fontWeight: "700", flex: 1 },
  jsonValue: { color: "#0f172a", fontSize: 12, flex: 1.5, textAlign: "right" },

  // Sub-sections
  subSectionLabel: {
    marginTop: 8,
    color: "#0f172a",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
    paddingBottom: 2,
  },
  notesText: {
    color: "#475569",
    fontSize: 12,
    fontStyle: "italic",
    lineHeight: 18,
  },

  // Line items
  lineItemRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
    paddingVertical: 2,
  },
  lineItemName: {
    color: "#0f172a",
    fontSize: 11,
    flex: 1.2,
    fontWeight: "600",
  },
  lineItemAmt: { color: "#475569", fontSize: 11, flex: 1, textAlign: "right" },

  // Warnings
  warningBox: {
    backgroundColor: "#fffbeb",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#fde68a",
    padding: 8,
    gap: 2,
  },
  warningSmall: { color: "#92400e", fontSize: 11 },

  // Stage info row
  stageRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 4,
  },
  stageMeta: { color: "#94a3b8", fontSize: 10 },
  stageMetaAI: { color: "#4338ca", fontWeight: "700" },

  // Raw / toggle boxes
  toggleBtn: {
    alignSelf: "flex-start",
    marginTop: 4,
    backgroundColor: "#f1f5f9",
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  toggleBtnText: { color: "#475569", fontSize: 11, fontWeight: "700" },
  rawBox: {
    backgroundColor: "#f8fafc",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    maxHeight: 200,
    padding: 8,
  },
  rawText: {
    color: "#334155",
    fontSize: 11,
    lineHeight: 16,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },

  resultMeta: { color: "#334155", fontSize: 12 },
});

export default App;
