// ::: Code Generated by Copilot [3b0897cb-a4be-4ca8-b2ad-1b7fcb6f444c]. This comment will be removed automatically after the file is saved :::
// ::: Code Generated by Copilot [4be8cbaf-0f99-4832-bbd0-07899292a516]. This comment will be removed automatically after the file is saved :::
// ::: Code Generated by Copilot [7decb3da-a0ff-40ba-a6d4-43e2853112c5]. This comment will be removed automatically after the file is saved :::
// ::: Code Generated by Copilot [7a671463-c1ac-4c59-a876-40c6ff5d8962]. This comment will be removed automatically after the file is saved :::
import React, { useEffect, useMemo, useState } from "react";
import {
  ActivityIndicator,
  Alert,
  Platform,
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { launchImageLibrary } from "react-native-image-picker";
import {
  DataLift,
  DataLiftScanner,
  DocumentScanResult,
  ImageQuality,
  isDataLiftAvailable,
  useDataLift,
} from "react-native-datalift";

type DemoMode = "component" | "hook";

// ::: Code Generated by Copilot [7a671463-c1ac-4c59-a876-40c6ff5d8962]. This comment will be removed automatically after the file is saved :::
const JsonField = ({
  label,
  value,
}: {
  label: string;
  value: unknown;
}) => {
  const display =
    value === undefined || value === null || value === ""
      ? "—"
      : typeof value === "object"
        ? JSON.stringify(value)
        : String(value);

  return (
    <View style={styles.jsonRow}>
      <Text style={styles.jsonKey}>{label}</Text>
      <Text style={styles.jsonValue} numberOfLines={2}>
        {display}
      </Text>
    </View>
  );
};

// ::: Code Generated by Copilot [7a671463-c1ac-4c59-a876-40c6ff5d8962]. This comment will be removed automatically after the file is saved :::
const DesignedJsonCard = ({
  title,
  data,
}: {
  title: string;
  data: Record<string, any>;
}) => {
  const header = data?.header ?? {};
  const totals = data?.totals ?? {};
  const vendor = data?.vendor ?? {};
  const audit = data?.audit ?? {};
  const model = audit?.model ?? {};

  return (
    <View style={styles.schemaCard}>
      <Text style={styles.schemaTitle}>{title}</Text>
      <JsonField label="Document Type" value={data?.document_type} />
      <JsonField label="Invoice Number" value={header?.invoice_number} />
      <JsonField label="Receipt Number" value={header?.receipt_number} />
      <JsonField label="Date Issued" value={header?.date_issued} />
      <JsonField label="Vendor" value={vendor?.name} />
      <JsonField label="Grand Total" value={totals?.grand_total} />
      <JsonField label="Amount Due" value={totals?.amount_due} />
      <JsonField label="Model Used" value={model?.layoutlmv3_used} />
      <JsonField label="Model Runtime" value={model?.layoutlmv3_runtime} />

      <Text style={styles.rawLabel}>Full JSON</Text>
      <Text style={styles.rawPreview} numberOfLines={14}>
        {JSON.stringify(data, null, 2)}
      </Text>
    </View>
  );
};

const ResultTile = ({ result }: { result: DocumentScanResult }) => {
  // ::: Code Generated by Copilot [3b0897cb-a4be-4ca8-b2ad-1b7fcb6f444c]. This comment will be removed automatically after the file is saved :::
  const summary = useMemo(() => {
    const data: any = result.structuredData ?? {};
    const enhanced = data.enhanced ?? {};
    return {
      type: String(result.documentType ?? "generic").toUpperCase(),
      confidence: `${Math.round((result.confidence ?? 0) * 100)}%`,
      total:
        enhanced?.summary?.totalAmount ??
        data.totalAmount ??
        enhanced?.summary?.balanceDue ??
        data.balanceDue,
      invoice:
        enhanced?.documentInfo?.invoiceNumber ??
        data.invoiceNumber ??
        "not found",
      lineItems:
        enhanced?.lineItems?.length ??
        data.lineItems?.length ??
        data.items?.length ??
        0,
    };
  }, [result]);

  return (
    <View style={styles.resultCard}>
      <View style={styles.resultTopRow}>
        <Text style={styles.resultType}>{summary.type}</Text>
        <Text style={styles.badge}>{summary.confidence}</Text>
      </View>
      <Text style={styles.resultMeta}>
        Invoice/Receipt No: {summary.invoice}
      </Text>
      <Text style={styles.resultMeta}>Line items: {summary.lineItems}</Text>
      <Text style={styles.resultMeta}>
        Total: {summary.total ?? "not found"}
      </Text>
      <Text style={styles.rawLabel}>JSON preview</Text>
      <Text style={styles.rawPreview} numberOfLines={8}>
        {JSON.stringify(result.structuredData, null, 2)}
      </Text>
    </View>
  );
};

const App = () => {
  // ::: Code Generated by Copilot [3b0897cb-a4be-4ca8-b2ad-1b7fcb6f444c]. This comment will be removed automatically after the file is saved :::
  // ::: Code Generated by Copilot [98a9f3f9-3862-4e8a-a143-31f658010c2f]. This comment will be removed automatically after the file is saved :::
  // ::: Code Generated by Copilot [4be8cbaf-0f99-4832-bbd0-07899292a516]. This comment will be removed automatically after the file is saved :::
  const layoutLMv3ModelPath = "layoutlmv3_invoice.onnx";
  const layoutLMv3LabelsPath = "layoutlmv3_labels.txt";
  const [mode, setMode] = useState<DemoMode>("component");
  const [componentResults, setComponentResults] = useState<
    DocumentScanResult[]
  >([]);
  const [schemaResult, setSchemaResult] = useState<Record<
    string,
    unknown
  > | null>(null);
  const [modelReady, setModelReady] = useState(false);
  const [modelError, setModelError] = useState<string | null>(null);
  const [compatibility, setCompatibility] = useState<{
    compatible: boolean;
    error?: string;
    warnings?: string[];
  } | null>(null);

  // ::: Code Generated by Copilot [1a9b67e5-e87d-4f97-b103-c8b0c595eb95]. This comment will be removed automatically after the file is saved :::
  const modelCompatible = compatibility?.compatible === true;

  const hook = useDataLift({
    language: "eng",
    confidenceThreshold: 0.65,
    enableDebug: __DEV__,
    layoutLMv3ModelPath,
    layoutLMv3LabelsPath,
    requireLayoutLMv3: true,
  });

  // ::: Code Generated by Copilot [4be8cbaf-0f99-4832-bbd0-07899292a516]. This comment will be removed automatically after the file is saved :::
  // ::: Code Generated by Copilot [9f653704-517a-4734-b067-9e5ec72168af]. This comment will be removed automatically after the file is saved :::
  // ::: Code Generated by Copilot [7decb3da-a0ff-40ba-a6d4-43e2853112c5]. This comment will be removed automatically after the file is saved :::
  useEffect(() => {
    let active = true;

    const configureModel = async () => {
      try {
        await DataLift.configureLayoutLMv3({
          modelPath: layoutLMv3ModelPath,
          labelsPath: layoutLMv3LabelsPath,
        });
        const compatibilityResult = await DataLift.checkLayoutLMv3Compatibility(
          {
            modelPath: layoutLMv3ModelPath,
            labelsPath: layoutLMv3LabelsPath,
          },
        );

        if (!active) return;
        setCompatibility({
          compatible: compatibilityResult.compatible,
          error: compatibilityResult.error,
          warnings: compatibilityResult.warnings,
        });
        setModelReady(compatibilityResult.compatible);
        setModelError(
          compatibilityResult.compatible
            ? null
            : compatibilityResult.error || "Model compatibility check failed",
        );
      } catch (err) {
        if (!active) return;
        const message = err instanceof Error ? err.message : String(err);
        setModelReady(false);
        setCompatibility({
          compatible: false,
          error: message,
          warnings: [],
        });
        setModelError(message);
      }
    };

    configureModel();
    return () => {
      active = false;
    };
  }, [layoutLMv3LabelsPath, layoutLMv3ModelPath]);

  const currentResults = mode === "component" ? componentResults : hook.results;
  const latestStructuredData =
    (currentResults[0]?.structuredData as Record<string, unknown> | undefined) ??
    null;

  const clearCurrent = () => {
    if (mode === "component") {
      setComponentResults([]);
      return;
    }
    hook.reset();
    setSchemaResult(null);
  };

  // ::: Code Generated by Copilot [98a9f3f9-3862-4e8a-a143-31f658010c2f]. This comment will be removed automatically after the file is saved :::
  const printLatestJsonToConsole = () => {
    if (currentResults.length === 0 && !schemaResult) {
      Alert.alert("No Results", "Run scan/pick first, then print JSON.");
      return;
    }

    if (currentResults.length > 0) {
      const latest = currentResults[0];
      console.log("[DataLift][LatestResult]", JSON.stringify(latest, null, 2));
      console.log(
        "[DataLift][LatestStructuredData]",
        JSON.stringify(latest.structuredData ?? {}, null, 2),
      );
    }
    if (schemaResult) {
      console.log(
        "[DataLift][LayoutLMv3Schema]",
        JSON.stringify(schemaResult, null, 2),
      );
    }
    Alert.alert("Printed", "Latest JSON printed in Metro console.");
  };

  // ::: Code Generated by Copilot [1a9b67e5-e87d-4f97-b103-c8b0c595eb95]. This comment will be removed automatically after the file is saved :::
  const ensureModelCompatibility = () => {
    if (modelCompatible) return true;
    Alert.alert(
      "Model Not Ready",
      compatibility?.error ||
        modelError ||
        "LayoutLMv3 compatibility check failed. Configure a compatible model and labels first.",
    );
    return false;
  };

  // ::: Code Generated by Copilot [1a9b67e5-e87d-4f97-b103-c8b0c595eb95]. This comment will be removed automatically after the file is saved :::
  const captureWithCompatibilityCheck = async () => {
    if (!ensureModelCompatibility()) return;
    await hook.captureAndProcess({ quality: ImageQuality.HIGH });
  };

  // ::: Code Generated by Copilot [1a9b67e5-e87d-4f97-b103-c8b0c595eb95]. This comment will be removed automatically after the file is saved :::
  const pickWithCompatibilityCheck = async () => {
    if (!ensureModelCompatibility()) return;
    await hook.pickAndProcess({ multiple: true, maxImages: 5 });
  };

  // ::: Code Generated by Copilot [0b1436a0-8f2e-4ef0-a255-f6f5dbd8694c]. This comment will be removed automatically after the file is saved :::
  const pickAndExtractSchema = async () => {
    if (!ensureModelCompatibility()) return;
    try {
      const response = await new Promise<any>((resolve) => {
        launchImageLibrary(
          {
            mediaType: "photo",
            selectionLimit: 4,
          },
          (res) => resolve(res),
        );
      });

      if (response?.didCancel) return;
      if (response?.errorCode) {
        Alert.alert(
          "Picker Error",
          response.errorMessage || response.errorCode,
        );
        return;
      }

      const assets = Array.isArray(response?.assets) ? response.assets : [];
      const uris = assets.map((asset: any) => asset?.uri).filter(Boolean);
      const fileNames = assets
        .map((asset: any) => asset?.fileName)
        .filter(Boolean);

      if (uris.length === 0) {
        Alert.alert("No image", "Please select at least one image.");
        return;
      }

      const result = await hook.extractInvoiceSchema(uris, fileNames);
      setSchemaResult(result);
      const audit = (result?.audit as any) ?? {};
      const model = (audit?.model as any) ?? {};
      const used = model?.layoutlmv3_used === true ? "Yes" : "No";
      Alert.alert("Schema Extracted", `LayoutLMv3 used: ${used}`);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      Alert.alert("LayoutLMv3 Error", message);
    }
  };

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="dark-content" backgroundColor="#f8fafc" />
      <ScrollView contentContainerStyle={styles.content}>
        <View style={styles.hero}>
          <Text style={styles.title}>DataLift Example</Text>
          <Text style={styles.subtitle}>
            Minimal demo with only two implementations: UI component + hook API.
          </Text>
        </View>

        {!isDataLiftAvailable && (
          <View style={styles.warning}>
            <Text style={styles.warningText}>
              Native module not linked.{" "}
              {Platform.OS === "ios"
                ? "Run pod install + rebuild."
                : "Run a clean Android build."}
            </Text>
          </View>
        )}

        <View style={styles.segmentWrap}>
          <TouchableOpacity
            style={[
              styles.segment,
              mode === "component" && styles.segmentActive,
            ]}
            onPress={() => setMode("component")}
          >
            <Text
              style={[
                styles.segmentText,
                mode === "component" && styles.segmentTextActive,
              ]}
            >
              UI Component
            </Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.segment, mode === "hook" && styles.segmentActive]}
            onPress={() => setMode("hook")}
          >
            <Text
              style={[
                styles.segmentText,
                mode === "hook" && styles.segmentTextActive,
              ]}
            >
              Hook API
            </Text>
          </TouchableOpacity>
        </View>

        {mode === "component" ? (
          <View style={styles.card}>
            <Text style={styles.sectionTitle}>
              Implementation 1: DataLiftScanner
            </Text>
            <Text style={styles.sectionText}>
              Uses the built-in UI component. Quickest integration path.
            </Text>
            <DataLiftScanner
              onResults={(results) =>
                setComponentResults((prev) => [...results, ...prev])
              }
              onError={(error) => Alert.alert("Scanner Error", error.message)}
              multiImage
              maxImages={5}
              quality={ImageQuality.HIGH}
              language="eng"
              enableDebug={__DEV__}
              showPreview
            />
          </View>
        ) : (
          <View style={styles.card}>
            <Text style={styles.sectionTitle}>
              Implementation 2: useDataLift
            </Text>
            <Text style={styles.sectionText}>
              Programmatic flow with your own controls and presentation layer.
            </Text>
            <Text style={styles.schemaMeta}>
              Native model: {modelReady ? "configured" : "not configured"}
            </Text>
            <Text style={styles.schemaMeta}>
              Compatibility: {compatibility?.compatible ? "pass" : "fail"}
            </Text>
            {!!compatibility?.warnings?.length && (
              <Text style={styles.schemaMeta}>
                Warning: {compatibility.warnings[0]}
              </Text>
            )}
            <Text style={styles.schemaMeta}>
              Required: fine-tuned token-classification model + labels map
              (O/B-/I- tags).
            </Text>
            {!!modelError && <Text style={styles.errorText}>{modelError}</Text>}
            <View style={styles.buttonRow}>
              <TouchableOpacity
                style={[
                  styles.button,
                  (hook.loading || !modelCompatible) && styles.buttonDisabled,
                ]}
                disabled={hook.loading || !modelCompatible}
                onPress={captureWithCompatibilityCheck}
              >
                <Text style={styles.buttonText}>Capture</Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={[
                  styles.button,
                  styles.buttonSecondary,
                  (hook.loading || !modelCompatible) && styles.buttonDisabled,
                ]}
                disabled={hook.loading || !modelCompatible}
                onPress={pickWithCompatibilityCheck}
              >
                <Text style={styles.buttonText}>Pick Images</Text>
              </TouchableOpacity>
            </View>
            <TouchableOpacity
              style={[
                styles.button,
                styles.schemaBtn,
                (hook.loading || !modelCompatible) && styles.buttonDisabled,
              ]}
              disabled={hook.loading || !modelCompatible}
              onPress={pickAndExtractSchema}
            >
              <Text style={styles.buttonText}>
                Extract Schema (Native Model)
              </Text>
            </TouchableOpacity>

            {hook.loading && (
              <View style={styles.loadingBox}>
                <ActivityIndicator color="#0ea5e9" />
                <Text style={styles.loadingText}>
                  Processing {Math.round(hook.progress)}%
                </Text>
              </View>
            )}

            {hook.error && (
              <Text style={styles.errorText}>{hook.error.message}</Text>
            )}

            {schemaResult && (
              <DesignedJsonCard
                title="LayoutLMv3 Schema Output"
                data={schemaResult as Record<string, any>}
              />
            )}
          </View>
        )}

        {latestStructuredData && (
          <DesignedJsonCard
            title="Latest Scan Structured Data"
            data={latestStructuredData as Record<string, any>}
          />
        )}

        <View style={styles.resultsHeader}>
          <Text style={styles.resultsTitle}>
            Results ({currentResults.length})
          </Text>
          <View style={styles.resultsActions}>
            <TouchableOpacity
              onPress={printLatestJsonToConsole}
              style={styles.consoleBtn}
            >
              <Text style={styles.consoleBtnText}>JSON Console</Text>
            </TouchableOpacity>
            <TouchableOpacity onPress={clearCurrent} style={styles.clearBtn}>
              <Text style={styles.clearBtnText}>Clear</Text>
            </TouchableOpacity>
          </View>
        </View>

        {currentResults.length === 0 ? (
          <View style={styles.emptyState}>
            <Text style={styles.emptyTitle}>No output yet</Text>
            <Text style={styles.emptyText}>
              Scan or pick an image to see parsed JSON output.
            </Text>
          </View>
        ) : (
          currentResults.map((result, index) => (
            <ResultTile
              key={`${result.processingTime}-${index}`}
              result={result}
            />
          ))
        )}
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8fafc" },
  content: { padding: 16, paddingBottom: 28, gap: 12 },
  hero: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 16,
  },
  title: { fontSize: 24, fontWeight: "800", color: "#0f172a" },
  subtitle: { marginTop: 4, color: "#475569", fontSize: 13, lineHeight: 18 },
  warning: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#fde68a",
    backgroundColor: "#fffbeb",
    padding: 12,
  },
  warningText: { color: "#92400e", fontSize: 12, fontWeight: "600" },
  segmentWrap: {
    flexDirection: "row",
    backgroundColor: "#e2e8f0",
    borderRadius: 12,
    padding: 4,
  },
  segment: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  segmentActive: { backgroundColor: "#ffffff" },
  segmentText: { color: "#334155", fontWeight: "700", fontSize: 13 },
  segmentTextActive: { color: "#0f172a" },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 14,
    gap: 10,
  },
  sectionTitle: { fontSize: 15, fontWeight: "800", color: "#0f172a" },
  sectionText: { fontSize: 13, color: "#475569", lineHeight: 18 },
  buttonRow: { flexDirection: "row", gap: 10 },
  button: {
    flex: 1,
    backgroundColor: "#2563eb",
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  buttonSecondary: { backgroundColor: "#0f766e" },
  buttonDisabled: { opacity: 0.5 },
  buttonText: { color: "#ffffff", fontWeight: "700", fontSize: 13 },
  schemaBtn: { marginTop: 2, backgroundColor: "#7c3aed" },
  loadingBox: { flexDirection: "row", alignItems: "center", gap: 8 },
  loadingText: { color: "#334155", fontSize: 12, fontWeight: "600" },
  errorText: { color: "#be123c", fontSize: 12, fontWeight: "600" },
  schemaCard: {
    backgroundColor: "#f8fafc",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    padding: 10,
    gap: 4,
  },
  schemaTitle: { color: "#0f172a", fontWeight: "800", fontSize: 13 },
  schemaMeta: { color: "#334155", fontSize: 12 },
  jsonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  jsonKey: { color: "#475569", fontSize: 12, fontWeight: "700", flex: 1 },
  jsonValue: { color: "#0f172a", fontSize: 12, flex: 1.2, textAlign: "right" },
  resultsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 2,
  },
  resultsActions: { flexDirection: "row", gap: 8 },
  resultsTitle: { fontSize: 16, fontWeight: "800", color: "#0f172a" },
  clearBtn: {
    backgroundColor: "#e2e8f0",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  clearBtnText: { color: "#334155", fontWeight: "700", fontSize: 12 },
  consoleBtn: {
    backgroundColor: "#0f766e",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  consoleBtnText: { color: "#ffffff", fontWeight: "700", fontSize: 12 },
  emptyState: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 16,
    alignItems: "center",
  },
  emptyTitle: { fontWeight: "800", color: "#0f172a", marginBottom: 4 },
  emptyText: { color: "#64748b", fontSize: 12 },
  resultCard: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 12,
    gap: 6,
  },
  resultTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  resultType: { fontWeight: "800", color: "#0f172a", fontSize: 14 },
  badge: {
    backgroundColor: "#ecfeff",
    borderWidth: 1,
    borderColor: "#a5f3fc",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 3,
    color: "#0e7490",
    fontWeight: "800",
    fontSize: 11,
  },
  resultMeta: { color: "#334155", fontSize: 12 },
  rawLabel: { marginTop: 2, color: "#0f172a", fontSize: 12, fontWeight: "700" },
  rawPreview: {
    backgroundColor: "#f8fafc",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 8,
    color: "#334155",
    fontSize: 11,
    lineHeight: 16,
  },
});

export default App;
