require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = "react-native-datalift"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = package["homepage"]
  s.license      = package["license"]
  s.authors      = "DataLift"

  # iOS 13+ required — Vision framework (OCR) needs iOS 13
  s.platforms    = { :ios => "13.0" }

  s.source       = {
    :git => package.dig("repository", "url") || "",
    :tag => "#{s.version}"
  }

  # Include the ObjC bridge (.m) and all Swift sources
  s.source_files = "ios/**/*.{h,m,mm,swift}"

  # ::: Code Generated by Copilot a1b2c3d4-e5f6-7890-abcd-ef1234567890. This comment will be removed automatically after the file is saved :::
  # Bundle fine-tuned LayoutLMv3 label map and BPE vocabulary so they are
  # available in Bundle.main without any manual Xcode project changes.
  s.resources = ["datalift-models/labels.json", "datalift-models/vocab.json"]

  # Required for Swift ↔ ObjC interop and module map generation
  s.pod_target_xcconfig = {
    "DEFINES_MODULE"          => "YES",
    "SWIFT_COMPILATION_MODE"  => "wholemodule",
    "BUILD_LIBRARY_FOR_DISTRIBUTION" => "NO"
  }

  # ::: Code Generated by Copilot b7e3a21f-4c8d-4b9e-a5f1-2d8e9c0f3a7b. This comment will be removed automatically after the file is saved :::
  # libz is used by DataLiftZipExtractor.m for raw-DEFLATE decompression of
  # downloaded .mlpackage.zip CoreML model archives.
  s.libraries = "z"

  # Old Architecture (bridge) — works via interop layer on RN 0.76+
  s.dependency "React-Core"

end
