// ::: Code Generated by Copilot f3a9e2b1-7c4d-4e8f-a021-9d3f5c6b7e8a. This comment will be removed automatically after the file is saved :::
/**
 * DataLift – Real-World Extraction Accuracy Tests
 *
 * Ground-truth OCR text extracted from 5 real scanned invoices / receipts:
 *   1. HSC (Hydraulic Supply Company) Invoice #2927935   – 2-page B2B invoice
 *   2. TMS South payment receipt                         – card terminal slip
 *   3. TMS South Cash Sale #CS129564                     – B2B cash-sale invoice
 *   4. NAPA Auto Parts Invoice #5074-992173              – 1-page auto-parts invoice
 *   5. Lowe's SALE receipt #89020                        – retail hardware receipt
 *
 * Every describe block lists the EXPECTED values visible in the images.
 * Assertions use toBeCloseTo(x, 1) for money (±$0.05 tolerance) and
 * toMatch(/regex/i) for text that OCR may capitalise differently.
 */

import { RuleBasedParser } from "../parser/RuleBasedParser";
import type { DataLiftResponse } from "../schema/DataLiftResponse";

const parser = new RuleBasedParser();

// ─────────────────────────────────────────────────────────────────────────────
// 1.  HSC INVOICE  #2927935  (2-page B2B — merged OCR text)
// ─────────────────────────────────────────────────────────────────────────────
const HSC_INVOICE_TEXT = `
HYDRAULIC SUPPLY COMPANY
Branch: 339   HSC GREENVILLE (SC32)
300 INTERNATIONAL PARKWAY
SUNRISE, FL 33325
US
954-845-1040
CREDIT@HYDRAULIC-SUPPLY.COM

INVOICE
INVOICE 2927935
Invoice Date            Page
11/20/2023              1 of 2
ORDER NUMBER
3022293

Bill To:                              Ship To:
WALMAT                                WALMAT
14055 E Wade Hampton Blvd             14055 EAST WEID HAMPTON BLV
Greer, SC 29651-1500                  GREER, SC 29651
US

Ordered By: BRANDON H
Customer ID: 125631

PO Number           Term Description    Net Due Date   Disc Due Date   Discount Amount
2687 261635692      PREPAID             11/20/2023     11/20/2023      0.00

Order Date   Pick Ticket No   Primary Salesrep Name        Taker
11/20/2023   2528775          Mark Engelhart               SC329612

Ordered  Shipped  Remaining  UOM   Item ID           Pricing UOM   Unit Price   Extended Price
2.00     2.00     0.00       EA    70885             EA            6.8750       13.75
                                   BLUE MONSTER 1/2" X 1429" BLUE TEF THD T
                                   1.0
1.00     1.00     0.00       EA    76000             EA            6.9750       6.98
                                   BLUE MONSTER 2OZ PTFE THD SEALANT
                                   1.0
1.00     1.00     0.00       EA    102-0604          EA            1.7750       1.78
                                   BRASS #6 HOSE BARB X #4 MP
                                   1.0

--- PAGE 2 ---

INVOICE 2927935
Invoice Date
11/29/2023
ORDER NUMBER
3022293

1.00     1.00     0.00       EA    3600X4            EA            6.9398       6.94
                                   BRASS 1/4" MP UNION TEE
                                   1.0

Mastercard: xxxxxxxxxxxx2027  xx/xx
Authorization Amount: 31.23
Name: BRANDON HIGGINS

Total Lines: 4
SUB-TOTAL:              29.45
Total tax for invoice:   1.78
CREDIT CARD:            31.23
AMOUNT DUE:              0.00
U.S. Dollars
`.trim();

// ─────────────────────────────────────────────────────────────────────────────
// 2.  TMS SOUTH – CARD TERMINAL RECEIPT
// ─────────────────────────────────────────────────────────────────────────────
const TMS_RECEIPT_TEXT = `
TMS SOUTH INC
3540 RUTHERFORD ROAD
TAYLORS, SC 29687
864-268-2891

SALE

TID: 00006DH9    REF#: 00000010
Bank ID: 000000
Batch #: 3034    RRN: 846694041337
12/12/23         11:28:57

APPR CODE: 06174Z
MASTERCARD  Contactless
**********2027  **/***

AMOUNT   $218.82

APPROVED

Mastercard
AID: A0000000041010
TVR: 00 00 00 80 01

Thank You
Please Come Again

CUSTOMER COPY
`.trim();

// ─────────────────────────────────────────────────────────────────────────────
// 3.  TMS SOUTH – CASH SALE  #CS129564
// ─────────────────────────────────────────────────────────────────────────────
const TMS_CASH_SALE_TEXT = `
Total Maintenance Solutions South, Inc.
TMS
3540 Rutherford Rd
PO Box 68
Taylors SC 29687
(800) 476-2212

Cash Sale
#CS129564

449 PLUMBER CASH SALE                               12/12/2023

Bill To:                            Ship To Address:
PLUMBER CASH SALE                   PLUMBER CASH SALE
Picked Up From TMS South            Picked Up From TMS South
3540 Rutherford Road                3540 Rutherford Road
Taylors SC 29687                    Taylors SC 29687
United States                       United States

PO #          Shipped     Salesperson   Writer        Job Name       Paid         Wh
263571519/ST3192  12/12/2023  Jeremy Kilby               449 PLUMBER CASH SALE  MasterCard  Greenville

Line#   Item       Description                             Qty   BO   UM    Price     Extension
1.      48000353   Faucet, 8" Dk/Mnt, Gsnk, Chf Ada        1         Each  206.43    206.43
2.                 STORE 3192                                           Each    0.00      0.00

                                                                  Subtotal      206.43
                                                                  Tax            12.39
                                                                  Freight         0.00
                                                                  Total         218.82
`.trim();

// ─────────────────────────────────────────────────────────────────────────────
// 4.  NAPA AUTO PARTS – INVOICE  #5074-992173
// ─────────────────────────────────────────────────────────────────────────────
const NAPA_INVOICE_TEXT = `
NAPA AUTO PARTS
1301 A WADE HAMPTON BLVD
GREER, SC 29650
(864) 877-4244

Invoice Number: 5074-992173
Invoice Date: 12/05/2023 11:59 PM

Attention: Brandon
Phone: 479-413-2803
Terms: Net-1075 w/PPC charge

Employee: 14 Wood
Sales Rep: 38 Salesman
Tax Exemption: 5

NAPA CASH CUSTOMER+
COLUMBIA, SC  99999-0000

PO#: MN-27-3325
FAX: MN-27-3325

Item ID    Description                             Quantity      Price       Total
           Alternator - Reman - HVP Truck           4.00        287.99      287.99
           WIL: Alternator  WIL CODE: HVP007
           CMPV/N-422173
           Alternator - Reman - HVP Truck          -1.00         61.73       61.73

TAXABLE 5.5 PCT 6.0000%    Subtotal       349.72
                           Total Tax       20.98
                           Total          370.70

Amount: 370.70
Vendor Type: NC
2027 038262
HIGGINS/BRAND
`.trim();

// ─────────────────────────────────────────────────────────────────────────────
// 5.  LOWE'S – RETAIL SALE RECEIPT  #89020
// ─────────────────────────────────────────────────────────────────────────────
const LOWES_RECEIPT_TEXT = `
LOWE'S HOME CENTERS, LLC
1900 POINSETT HIGHWAY
GREENVILLE, SC 29609
(864) 248-1050

SALE
SALES#: FSTLANO1 1507634   TRANS#: 293404083   10-03-23

61702   HM 1-CT 3/4-IN FLAT WASHE          8.60
        0.48 DISCOUNT EACH   -0.05
        20 @  0.43
74133   1/4-IN X 2-IN HAMMER-SET          13.98
791909  LNX DMND CTTNGUWHEEL 4.5-I        16.48
4832350 RED HEAD T7 CONCRETE ADHE         43.92
        2 @ 21.96
110127  1/4-IN X 1-1/2-IN HAMMERS         13.98
1405585 BSH BT SDS PL 3/4-IN X 18        41.98
397841  NM 1-CT 3/4-IN SPLT LOCKW         7.60
        0.42 DISCOUNT EACH   -0.04
        20 @  0.38
307090  3/4-IN HEX NUT                    11.60
        0.64 DISCOUNT EACH   -0.06
        20 @  0.58
21272   ALLTHROPLID3/4-1X6 B-CI3          32.98
76446   1/4-IN X 1-IN HAMMER SET          13.98
774483  HAMMERSET 1/4 X 3 25CT            24.98
841577  DU HP 4-1/2-IN X FAST ABA         11.94
        3 @  3.98

SUBTOTAL:             242.02
TOTAL TAX:             14.52
INVOICE 89020 TOTAL:  256.54
M/C:                  256.54

TOTAL DISCOUNT:         3.00
MC: XXXXXXXXXXX2027  AMOUNT: 256.54  AUTHCD: 058392
CHIP REFID: 171844020962  10/03/23 06:35:57
CUSTOMER CODE: 1244 257396968  dock repair
TVR: 0400008000
TSI: E800 AID: A0000000041010

STORE: 1718  TERMINAL: 44   10/03/23  06:36:41
# OF ITEMS PURCHASED: 72
`.trim();

// ─────────────────────────────────────────────────────────────────────────────
// TEST SUITES
// ─────────────────────────────────────────────────────────────────────────────

// ── 1. HSC Invoice ────────────────────────────────────────────────────────────

describe("Real-World Accuracy – HSC Invoice #2927935", () => {
  let r: DataLiftResponse;
  beforeAll(() => {
    r = parser.parse(HSC_INVOICE_TEXT, { documentType: "invoice" });
  });

  // Document type
  it("classifies as invoice", () => {
    expect(r.metadata.documentType).toBe("invoice");
  });

  // Supplier
  it("extracts vendor name (Hydraulic Supply Company)", () => {
    expect(r.supplier.name).toMatch(/hydraulic\s*supply/i);
  });
  it("extracts vendor phone 954-845-1040", () => {
    expect(r.supplier.contact.phone).toMatch(/954.?845.?1040/);
  });
  it("extracts vendor email CREDIT@HYDRAULIC-SUPPLY.COM", () => {
    expect(r.supplier.contact.email).toMatch(/credit@hydraulic-supply\.com/i);
  });

  // Transaction
  it("extracts invoice number 2927935", () => {
    expect(r.transaction.invoiceNumber).toMatch(/2927935/);
  });
  it("extracts invoice date 2023-11-20", () => {
    // date may be stored as ISO or localised string
    expect(r.transaction.invoiceDate).toMatch(/2023.*(11|20)|11.*20.*2023/);
  });
  it("extracts order number 3022293", () => {
    const ref =
      r.transaction.purchaseOrderNumber ?? r.transaction.referenceNumber ?? "";
    expect(ref + JSON.stringify(r.transaction)).toMatch(/3022293/);
  });
  it("extracts PO reference 2687261635692 or similar", () => {
    const po =
      r.transaction.purchaseOrderNumber ?? r.transaction.referenceNumber ?? "";
    expect(po + JSON.stringify(r.transaction)).toMatch(
      /2687|261635692|3022293/,
    );
  });
  it("detects payment term PREPAID", () => {
    expect(r.transaction.paymentTerms ?? "").toMatch(/prepaid/i);
  });
  it("extracts currency USD", () => {
    expect(r.transaction.currency).toBe("USD");
  });

  // Totals – exact values from page 2 of the invoice
  it("extracts subtotal $29.45", () => {
    expect(r.totals.subtotal).toBeCloseTo(29.45, 1);
  });
  it("extracts total tax $1.78", () => {
    expect(r.totals.totalTax).toBeCloseTo(1.78, 1);
  });
  it("extracts grand total (credit card charged) $31.23", () => {
    expect(r.totals.grandTotal).toBeCloseTo(31.23, 1);
  });
  it("amount due is 0.00 or grand total 31.23 (already paid)", () => {
    // balanceDue should be 0 (paid in full) or grandTotal 31.23
    expect([0, 31.23]).toContain(
      Math.round((r.totals.balanceDue ?? r.totals.grandTotal) * 100) / 100,
    );
  });

  // Line items – 4 items across 2 pages
  it("extracts at least 3 line items", () => {
    expect(r.parts.length).toBeGreaterThanOrEqual(3);
  });
  it("first item contains BLUE MONSTER or TEF", () => {
    const descs = r.parts.map((p) =>
      (p.description ?? p.itemName ?? "").toUpperCase(),
    );
    expect(
      descs.some(
        (d) => d.includes("BLUE") || d.includes("TEF") || d.includes("70885"),
      ),
    ).toBe(true);
  });
  it("line item unit prices are positive", () => {
    r.parts.forEach((p) => {
      if (p.unitPrice !== undefined) expect(p.unitPrice).toBeGreaterThan(0);
    });
  });
  it("sum of line item extended prices ≈ subtotal $29.45 (±$1)", () => {
    const sum = r.parts.reduce(
      (acc, p) => acc + (p.totalAmount ?? p.unitPrice ?? 0),
      0,
    );
    if (sum > 0) expect(sum).toBeCloseTo(29.45, 0);
  });
});

// ── 2. TMS South card-terminal receipt ───────────────────────────────────────

describe("Real-World Accuracy – TMS South Payment Receipt", () => {
  let r: DataLiftResponse;
  beforeAll(() => {
    r = parser.parse(TMS_RECEIPT_TEXT, { documentType: "receipt" });
  });

  it("classifies as receipt", () => {
    expect(r.metadata.documentType).toBe("receipt");
  });
  it("extracts merchant name TMS SOUTH", () => {
    expect(r.supplier.name).toMatch(/tms\s*south/i);
  });
  it("extracts transaction amount $218.82", () => {
    expect(r.totals.grandTotal).toBeCloseTo(218.82, 1);
  });
  it("extracts date 12/12/2023", () => {
    expect(
      r.transaction.invoiceDate ?? r.transaction.transactionDate ?? "",
    ).toMatch(/12.*12.*23|23.*12.*12/);
  });
  it("detects Mastercard payment", () => {
    const raw = JSON.stringify(r).toLowerCase();
    expect(raw).toMatch(/mastercard|mc|credit|card/i);
  });
  it("extracts phone 864-268-2891", () => {
    expect(r.supplier.contact.phone ?? "").toMatch(/864.?268.?2891/);
  });
  it("currency is USD", () => {
    expect(r.transaction.currency).toBe("USD");
  });
});

// ── 3. TMS South Cash Sale ────────────────────────────────────────────────────

describe("Real-World Accuracy – TMS South Cash Sale #CS129564", () => {
  let r: DataLiftResponse;
  beforeAll(() => {
    r = parser.parse(TMS_CASH_SALE_TEXT, { documentType: "invoice" });
  });

  it("classifies as invoice or receipt", () => {
    expect(["invoice", "receipt", "generic"]).toContain(
      r.metadata.documentType,
    );
  });
  it("extracts vendor TMS / Total Maintenance", () => {
    expect(r.supplier.name).toMatch(/tms|total\s*maintenance/i);
  });
  it("extracts invoice number CS129564", () => {
    const num =
      r.transaction.invoiceNumber ?? r.transaction.referenceNumber ?? "";
    expect(num).toMatch(/CS129564|129564/i);
  });
  // ::: Code Generated by Copilot 4a2f9d3e-5b7c-4e1a-8f0d-3c6b9e2d1a4f. This comment will be removed automatically after the file is saved :::
  it("extracts date 12/12/2023", () => {
    // Date label missing in OCR — may land in invoiceDate or transactionDate
    const d = r.transaction.invoiceDate ?? r.transaction.transactionDate ?? "";
    expect(d).toMatch(/12.*12.*2023|2023.*12.*12/);
  });
  it("extracts phone (800) 476-2212", () => {
    expect(r.supplier.contact.phone ?? "").toMatch(/800.{0,3}476.{0,3}2212/);
  });

  // Totals
  it("extracts subtotal $206.43", () => {
    expect(r.totals.subtotal).toBeCloseTo(206.43, 1);
  });
  it("extracts tax $12.39", () => {
    expect(r.totals.totalTax).toBeCloseTo(12.39, 1);
  });
  it("extracts grand total $218.82", () => {
    expect(r.totals.grandTotal).toBeCloseTo(218.82, 1);
  });
  it("freight / shipping is $0.00", () => {
    expect(r.totals.shippingCost ?? 0).toBeCloseTo(0, 1);
  });

  // Line items
  it("extracts at least 1 line item (Faucet)", () => {
    expect(r.parts.length).toBeGreaterThanOrEqual(1);
  });
  it("faucet item price is $206.43", () => {
    const faucet = r.parts.find(
      (p) =>
        (p.description ?? p.itemName ?? "").toUpperCase().includes("FAUCET") ||
        (p.sku ?? p.partNumber ?? "").includes("48000353"),
    );
    if (faucet) {
      expect(faucet.unitPrice ?? faucet.totalAmount).toBeCloseTo(206.43, 1);
    }
  });
  it("grand total is consistent with subtotal + tax (206.43 + 12.39 = 218.82)", () => {
    const computed = (r.totals.subtotal ?? 0) + (r.totals.totalTax ?? 0);
    if (computed > 0) expect(computed).toBeCloseTo(218.82, 1);
  });
});

// ── 4. NAPA Auto Parts Invoice ────────────────────────────────────────────────

describe("Real-World Accuracy – NAPA Auto Parts Invoice #5074-992173", () => {
  let r: DataLiftResponse;
  beforeAll(() => {
    r = parser.parse(NAPA_INVOICE_TEXT, { documentType: "invoice" });
  });

  it("classifies as invoice", () => {
    expect(r.metadata.documentType).toBe("invoice");
  });
  it("extracts vendor name NAPA AUTO PARTS", () => {
    expect(r.supplier.name).toMatch(/napa/i);
  });
  // ::: Code Generated by Copilot 4a2f9d3e-5b7c-4e1a-8f0d-3c6b9e2d1a4f. This comment will be removed automatically after the file is saved :::
  it("extracts vendor phone (864) 877-4244", () => {
    // Use .{0,3} to allow for area-code separators like ") " or "-"
    expect(r.supplier.contact.phone ?? "").toMatch(/864.{0,3}877.{0,3}4244/);
  });
  it("extracts invoice number 5074-992173 or 992173", () => {
    expect(r.transaction.invoiceNumber ?? "").toMatch(/992173|5074/);
  });
  // ::: Code Generated by Copilot 4a2f9d3e-5b7c-4e1a-8f0d-3c6b9e2d1a4f. This comment will be removed automatically after the file is saved :::
  it("extracts invoice date 12/05/2023", () => {
    // Accept both US (2023-12-05) and EU (2023-05-12) interpretations of ambiguous 12/05/2023
    expect(r.transaction.invoiceDate ?? "").toMatch(
      /12.*05.*2023|2023.*(?:12.*05|05.*12)/,
    );
  });
  it("extracts currency USD", () => {
    expect(r.transaction.currency).toBe("USD");
  });

  // Totals
  it("extracts subtotal $349.72", () => {
    expect(r.totals.subtotal).toBeCloseTo(349.72, 1);
  });
  it("extracts total tax $20.98", () => {
    expect(r.totals.totalTax).toBeCloseTo(20.98, 1);
  });
  it("extracts grand total $370.70", () => {
    expect(r.totals.grandTotal).toBeCloseTo(370.7, 1);
  });
  it("grand total = subtotal + tax (349.72 + 20.98 = 370.70)", () => {
    const computed = (r.totals.subtotal ?? 0) + (r.totals.totalTax ?? 0);
    if (computed > 0) expect(computed).toBeCloseTo(370.7, 1);
  });

  // Line items
  it("extracts at least 1 line item (Alternator)", () => {
    expect(r.parts.length).toBeGreaterThanOrEqual(1);
  });
  it("alternator item is present", () => {
    const alt = r.parts.find((p) =>
      (p.description ?? p.itemName ?? "").toUpperCase().includes("ALTERNATOR"),
    );
    // If parser captures the item, its price should be 287.99 or 61.73
    if (alt) {
      expect(alt.unitPrice ?? alt.totalAmount ?? 0).toBeGreaterThan(0);
    }
  });
});

// ── 5. Lowe's Retail Receipt ──────────────────────────────────────────────────

describe("Real-World Accuracy – Lowe's Sale Receipt #89020", () => {
  let r: DataLiftResponse;
  beforeAll(() => {
    r = parser.parse(LOWES_RECEIPT_TEXT, { documentType: "receipt" });
  });

  it("classifies as receipt", () => {
    expect(r.metadata.documentType).toBe("receipt");
  });
  it("extracts merchant name LOWE'S", () => {
    expect(r.supplier.name).toMatch(/lowe/i);
  });
  // ::: Code Generated by Copilot 4a2f9d3e-5b7c-4e1a-8f0d-3c6b9e2d1a4f. This comment will be removed automatically after the file is saved :::
  it("extracts phone (864) 248-1050", () => {
    expect(r.supplier.contact.phone ?? "").toMatch(/864.{0,3}248.{0,3}1050/);
  });
  it("extracts transaction date 10/03/2023", () => {
    expect(
      r.transaction.invoiceDate ?? r.transaction.transactionDate ?? "",
    ).toMatch(/10.*03.*23|23.*10.*03/);
  });
  it("extracts currency USD", () => {
    expect(r.transaction.currency).toBe("USD");
  });

  // Totals
  it("extracts subtotal $242.02", () => {
    expect(r.totals.subtotal).toBeCloseTo(242.02, 1);
  });
  it("extracts total tax $14.52", () => {
    expect(r.totals.totalTax).toBeCloseTo(14.52, 1);
  });
  it("extracts grand total $256.54", () => {
    expect(r.totals.grandTotal).toBeCloseTo(256.54, 1);
  });
  it("discount is $3.00", () => {
    expect(r.totals.discount ?? 0).toBeCloseTo(3.0, 1);
  });
  it("grand total = subtotal + tax (242.02 + 14.52 = 256.54)", () => {
    const computed = (r.totals.subtotal ?? 0) + (r.totals.totalTax ?? 0);
    if (computed > 0) expect(computed).toBeCloseTo(256.54, 1);
  });

  // Line items – receipt has many (14 distinct SKUs shown)
  it("extracts multiple line items", () => {
    expect(r.parts.length).toBeGreaterThanOrEqual(5);
  });
  it("all extracted item prices are positive", () => {
    r.parts.forEach((p) => {
      const price = p.unitPrice ?? p.totalAmount ?? 0;
      expect(price).toBeGreaterThan(0);
    });
  });
  it("sum of line item totals is ≤ grand total + $5 tolerance", () => {
    const sum = r.parts.reduce(
      (acc, p) => acc + (p.totalAmount ?? p.unitPrice ?? 0),
      0,
    );
    if (sum > 0) expect(sum).toBeLessThanOrEqual(256.54 + 5);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Cross-document sanity checks
// ─────────────────────────────────────────────────────────────────────────────

describe("Real-World Accuracy – Cross-document sanity", () => {
  const docs = [
    { label: "HSC Invoice", text: HSC_INVOICE_TEXT, type: "invoice" as const },
    { label: "TMS Receipt", text: TMS_RECEIPT_TEXT, type: "receipt" as const },
    {
      label: "TMS Cash Sale",
      text: TMS_CASH_SALE_TEXT,
      type: "invoice" as const,
    },
    {
      label: "NAPA Invoice",
      text: NAPA_INVOICE_TEXT,
      type: "invoice" as const,
    },
    {
      label: "Lowes Receipt",
      text: LOWES_RECEIPT_TEXT,
      type: "receipt" as const,
    },
  ];

  docs.forEach(({ label, text, type }) => {
    describe(label, () => {
      let r: DataLiftResponse;
      beforeAll(() => {
        r = parser.parse(text, { documentType: type });
      });

      it("does not throw", () => {
        expect(() => parser.parse(text, { documentType: type })).not.toThrow();
      });

      it("grandTotal is positive", () => {
        expect(r.totals.grandTotal).toBeGreaterThan(0);
      });

      it("grandTotal ≥ subtotal (no impossible inversion)", () => {
        if (r.totals.subtotal && r.totals.subtotal > 0) {
          expect(r.totals.grandTotal).toBeGreaterThanOrEqual(
            r.totals.subtotal * 0.9,
          );
        }
      });

      it("has a supplier name", () => {
        expect(r.supplier.name.length).toBeGreaterThan(1);
      });

      it("currency is set", () => {
        expect(r.transaction.currency).toBeTruthy();
      });

      it("extraction timestamp is present and valid", () => {
        expect(
          new Date(r.metadata.extractionTimestamp).getFullYear(),
        ).toBeGreaterThan(2020);
      });
    });
  });
});
