// ::: Code Generated by Copilot [7e6d4f2a-3c6e-4f58-98e5-7b0ad97d40f1]. This comment will be removed automatically after the file is saved :::
// ::: Code Generated by Copilot [4eeb8b8b-7bb6-4fee-af63-4d168db54d37]. This comment will be removed automatically after the file is saved :::
#import <React/RCTBridgeModule.h>

/**
 * Objective-C bridge for the DataLift Swift native module.
 * Exposes all methods to the React Native JavaScript layer.
 * Compatible with React Native 0.70+ (both old and new architecture)
 */
@interface RCT_EXTERN_MODULE(DataLift, NSObject)

RCT_EXTERN_METHOD(
  classifyDocument:(NSDictionary *)options
  resolve:(RCTPromiseResolveBlock)resolve
  reject:(RCTPromiseRejectBlock)reject
)

RCT_EXTERN_METHOD(
  extractTextNative:(NSDictionary *)options
  resolve:(RCTPromiseResolveBlock)resolve
  reject:(RCTPromiseRejectBlock)reject
)

RCT_EXTERN_METHOD(
  extractPDFPages:(NSDictionary *)options
  resolve:(RCTPromiseResolveBlock)resolve
  reject:(RCTPromiseRejectBlock)reject
)

// ::: Code Generated by Copilot [7e6d4f2a-3c6e-4f58-98e5-7b0ad97d40f1]. This comment will be removed automatically after the file is saved :::
RCT_EXTERN_METHOD(
  extractInvoiceSchema:(NSDictionary *)options
  resolve:(RCTPromiseResolveBlock)resolve
  reject:(RCTPromiseRejectBlock)reject
)

// ::: Code Generated by Copilot [f8190b85-d1ac-4418-9162-86ee5609e355]. This comment will be removed automatically after the file is saved :::
RCT_EXTERN_METHOD(
  configureLayoutLMv3:(NSDictionary *)options
  resolve:(RCTPromiseResolveBlock)resolve
  reject:(RCTPromiseRejectBlock)reject
)

// ::: Code Generated by Copilot [f8190b85-d1ac-4418-9162-86ee5609e355]. This comment will be removed automatically after the file is saved :::
RCT_EXTERN_METHOD(
  predictLayoutLMv3:(NSDictionary *)options
  resolve:(RCTPromiseResolveBlock)resolve
  reject:(RCTPromiseRejectBlock)reject
)

// ::: Code Generated by Copilot [4eeb8b8b-7bb6-4fee-af63-4d168db54d37]. This comment will be removed automatically after the file is saved :::
RCT_EXTERN_METHOD(
  checkLayoutLMv3Compatibility:(NSDictionary *)options
  resolve:(RCTPromiseResolveBlock)resolve
  reject:(RCTPromiseRejectBlock)reject
)

+ (BOOL)requiresMainQueueSetup
{
  return NO;
}

@end
