// ::: Code Generated by Copilot b7e3a21f-4c8d-4b9e-a5f1-2d8e9c0f3a7b. This comment will be removed automatically after the file is saved :::
#import "DataLiftZipExtractor.h"
#import <zlib.h>

static NSError *zipError(NSInteger code, NSString *msg) {
    return [NSError errorWithDomain:@"DataLiftZip"
                               code:code
                           userInfo:@{NSLocalizedDescriptionKey: msg}];
}

@implementation DataLiftZipExtractor

+ (BOOL)extractZip:(NSString *)zipPath
       toDirectory:(NSString *)destDir
             error:(NSError **)error {

    NSData *zipData = [NSData dataWithContentsOfFile:zipPath];
    if (!zipData) {
        if (error) *error = zipError(1, [NSString stringWithFormat:@"Cannot read zip: %@", zipPath]);
        return NO;
    }

    const uint8_t *bytes = (const uint8_t *)zipData.bytes;
    NSUInteger len = zipData.length;

    // ── Little-endian readers ─────────────────────────────────────────────────
#define U16(off) ((uint16_t)(bytes[(off)] | ((uint16_t)bytes[(off)+1] << 8)))
#define U32(off) ((uint32_t)(bytes[(off)] | ((uint32_t)bytes[(off)+1] << 8) \
                    | ((uint32_t)bytes[(off)+2] << 16) | ((uint32_t)bytes[(off)+3] << 24)))

    // ── 1. Locate End-of-Central-Directory (EOCD) ─────────────────────────────
    // Signature: PK\x05\x06  (0x06054b50 LE)
    NSInteger eocdOff = -1;
    // EOCD is at least 22 bytes from the end; comment can push it further back.
    NSInteger searchFrom = (NSInteger)len - 22;
    for (NSInteger i = searchFrom; i >= 0 && eocdOff < 0; i--) {
        if (bytes[i]   == 0x50 && bytes[i+1] == 0x4B &&
            bytes[i+2] == 0x05 && bytes[i+3] == 0x06) {
            eocdOff = i;
        }
    }
    if (eocdOff < 0) {
        if (error) *error = zipError(2, @"Invalid ZIP file: EOCD record not found");
        return NO;
    }

    uint16_t totalEntries = U16(eocdOff + 10);
    uint32_t cdOffset     = U32(eocdOff + 16);
    if ((NSUInteger)cdOffset >= len) {
        if (error) *error = zipError(3, @"Invalid ZIP file: central directory offset out of bounds");
        return NO;
    }

    // ── 2. Create destination directory ───────────────────────────────────────
    NSFileManager *fm = [NSFileManager defaultManager];
    [fm createDirectoryAtPath:destDir withIntermediateDirectories:YES attributes:nil error:nil];

    // ── 3. Walk Central Directory ─────────────────────────────────────────────
    NSUInteger cdPos = (NSUInteger)cdOffset;

    for (uint16_t idx = 0; idx < totalEntries; idx++) {
        if (cdPos + 46 > len) break;
        // Central directory file header signature: PK\x01\x02 (0x02014b50)
        if (U32(cdPos) != 0x02014B50U) break;

        uint16_t comprMethod      = U16(cdPos + 10);
        uint32_t compressedSz     = U32(cdPos + 20);
        uint32_t uncompressedSz   = U32(cdPos + 24);
        uint16_t fileNameLen      = U16(cdPos + 28);
        uint16_t extraLen         = U16(cdPos + 30);
        uint16_t commentLen       = U16(cdPos + 32);
        uint32_t localHeaderOff   = U32(cdPos + 42);

        NSString *fileName = nil;
        if (fileNameLen > 0 && cdPos + 46 + fileNameLen <= len) {
            fileName = [[NSString alloc] initWithBytes:bytes + cdPos + 46
                                                length:fileNameLen
                                              encoding:NSUTF8StringEncoding];
            // Fallback to Latin-1 if UTF-8 fails
            if (!fileName) {
                fileName = [[NSString alloc] initWithBytes:bytes + cdPos + 46
                                                    length:fileNameLen
                                                  encoding:NSISOLatin1StringEncoding];
            }
        }
        cdPos += 46 + fileNameLen + extraLen + commentLen;

        if (!fileName || fileName.length == 0) continue;

        NSString *destPath = [destDir stringByAppendingPathComponent:fileName];

        // Directory entry — just create it
        if ([fileName hasSuffix:@"/"]) {
            [fm createDirectoryAtPath:destPath withIntermediateDirectories:YES attributes:nil error:nil];
            continue;
        }

        // ── 4. Read Local File Header to find data offset ─────────────────────
        // Signature: PK\x03\x04 (0x04034b50)
        NSUInteger lfhOff = (NSUInteger)localHeaderOff;
        if (lfhOff + 30 > len) continue;
        if (U32(lfhOff) != 0x04034B50U) continue;

        uint16_t lfhNameLen  = U16(lfhOff + 26);
        uint16_t lfhExtraLen = U16(lfhOff + 28);
        NSUInteger dataOff   = lfhOff + 30 + lfhNameLen + lfhExtraLen;
        if (dataOff + compressedSz > len) continue;

        // ── 5. Create parent directories ──────────────────────────────────────
        NSString *parent = [destPath stringByDeletingLastPathComponent];
        [fm createDirectoryAtPath:parent withIntermediateDirectories:YES attributes:nil error:nil];

        // ── 6. Decompress / write ─────────────────────────────────────────────
        NSData *outData = nil;

        if (comprMethod == 0) {
            // STORED — copy verbatim
            outData = [NSData dataWithBytes:bytes + dataOff length:(NSUInteger)compressedSz];

        } else if (comprMethod == 8) {
            // DEFLATE — raw inflate (windowBits = -15 bypasses zlib wrapper)
            NSUInteger cap = uncompressedSz > 0 ? (NSUInteger)uncompressedSz : (NSUInteger)compressedSz * 4;
            NSMutableData *buf = [NSMutableData dataWithCapacity:cap];

            z_stream strm;
            memset(&strm, 0, sizeof(strm));
            strm.next_in  = (Bytef *)(bytes + dataOff);
            strm.avail_in = (uInt)compressedSz;

            if (inflateInit2(&strm, -15) != Z_OK) continue;

            uint8_t chunk[65536];
            int ret;
            do {
                strm.next_out  = chunk;
                strm.avail_out = sizeof(chunk);
                ret = inflate(&strm, Z_NO_FLUSH);
                NSUInteger produced = sizeof(chunk) - strm.avail_out;
                if (produced > 0) [buf appendBytes:chunk length:produced];
            } while (ret == Z_OK);

            inflateEnd(&strm);
            if (ret != Z_STREAM_END) continue; // decompression error — skip entry
            outData = buf;
        }

        if (outData) {
            [outData writeToFile:destPath atomically:YES];
        }
    }

#undef U16
#undef U32
    return YES;
}

@end
