// ::: Code Generated by Copilot b7e3a21f-4c8d-4b9e-a5f1-2d8e9c0f3a7b. This comment will be removed automatically after the file is saved :::
#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

/**
 * Minimal ZIP archive extractor for DataLift model download support.
 *
 * Handles STORED (method 0) and DEFLATE (method 8) entries so that
 * downloaded .mlpackage.zip archives can be expanded before CoreML
 * compilation without any third-party dependencies.
 *
 * Only call this from a background queue — decompression of large
 * model archives is CPU-intensive.
 */
@interface DataLiftZipExtractor : NSObject

/**
 * Extract all entries from the ZIP archive at @c zipPath into @c destDir.
 *
 * @param zipPath  Absolute path to the .zip file.
 * @param destDir  Absolute path to the destination directory (created if absent).
 * @param error    On failure, contains a descriptive error.
 * @return YES on success, NO on failure.
 */
+ (BOOL)extractZip:(NSString *)zipPath
       toDirectory:(NSString *)destDir
             error:(NSError *_Nullable __autoreleasing *_Nullable)error;

@end

NS_ASSUME_NONNULL_END
