import Foundation
import UIKit
import CoreML

final class LayoutLMv3OnnxEngine {
    private let minimumTokenConfidence = 0.88

    struct Prediction {
        let used: Bool
        let runtime: String
        let confidence: Double
        let fields: [String: Any]
        let warnings: [String]
    }

    private var model: MLModel?
    private var loadedModelPath: String?

    func predict(
        modelPath: String,
        labelsPath: String?,
        text: String,
        image: UIImage?
    ) throws -> Prediction {
        // Load labels — nil/missing path falls back to built-in defaults automatically
        let rawLabels = loadLabels(labelsPath: labelsPath)
        // Validate; if incompatible (e.g. downloaded file uses different vocab)
        // fall back to the built-in invoice defaults so extraction still runs.
        let labels: [Int: String]
        if isValidLabelMap(rawLabels) {
            labels = rawLabels
        } else {
            labels = defaultLabels()
        }
        let bpeVocab = loadVocab(modelPath: modelPath)
        let encoded = encode(text: text, bpeVocab: bpeVocab, maxSeqLen: 512)
        let mlModel = try getModel(modelPath: modelPath)
        let featureProvider = try buildFeatureProvider(
            model: mlModel,
            encoded: encoded,
            image: image,
            imageSide: 224
        )
        let output = try mlModel.prediction(from: featureProvider)
        let logits = try readLogits(from: output)
        let entities = decodeEntities(logits: logits, tokens: encoded.tokens, labels: labels)
        let fields = entitiesToFields(entities)
        let confidence = entities.map(\ .score).max() ?? 0
        var warnings: [String] = []
        if entities.isEmpty {
            warnings.append("No high-confidence entities survived post-processing")
        }
        if fields.isEmpty {
            warnings.append("No validated schema fields could be derived from model predictions")
        }

        return Prediction(
            used: !fields.isEmpty,
            runtime: "coreml-ios",
            confidence: confidence,
            fields: fields,
            warnings: warnings
        )
    }

    // ::: Code Generated by Copilot b7e3a21f-4c8d-4b9e-a5f1-2d8e9c0f3a7b. This comment will be removed automatically after the file is saved :::
    private func getModel(modelPath: String) throws -> MLModel {
        if let model, loadedModelPath == modelPath { return model }

        // MLModel requires a compiled .mlmodelc directory.
        // Priority:
        //   .mlpackage.zip → extract zip → compile → cache .mlmodelc
        //   .mlpackage     → compile → cache .mlmodelc
        //   anything else  → load directly (already a .mlmodelc or .mlmodel)
        let loadURL: URL

        if modelPath.hasSuffix(".mlpackage.zip") {
            // Strip ".zip" to get the expected .mlpackage directory path
            let unzippedPath = String(modelPath.dropLast(4))
            let compiledPath = unzippedPath + ".mlmodelc"
            let compiledURL  = URL(fileURLWithPath: compiledPath)

            if FileManager.default.fileExists(atPath: compiledPath) {
                // Already compiled on a previous launch — load directly
                loadURL = compiledURL
            } else {
                // Unzip if the .mlpackage directory isn't already present
                if !FileManager.default.fileExists(atPath: unzippedPath) {
                    let parentDir = URL(fileURLWithPath: unzippedPath).deletingLastPathComponent().path
                    do {
                        // Swift imports ObjC BOOL+NSError** methods as throwing functions
                        try DataLiftZipExtractor.extractZip(modelPath, toDirectory: parentDir)
                    } catch {
                        // The zip is corrupt (e.g. a downloaded HTML 404 page).
                        // Remove it so the next prepareModel() re-downloads cleanly.
                        try? FileManager.default.removeItem(atPath: modelPath)
                        throw error
                    }
                }
                // Compile the extracted .mlpackage
                let tmp = try MLModel.compileModel(at: URL(fileURLWithPath: unzippedPath))
                try? FileManager.default.removeItem(at: compiledURL)
                try FileManager.default.moveItem(at: tmp, to: compiledURL)
                loadURL = compiledURL
            }
        } else if modelPath.hasSuffix(".mlpackage") {
            let compiledPath = modelPath + ".mlmodelc"
            let compiledURL = URL(fileURLWithPath: compiledPath)
            if FileManager.default.fileExists(atPath: compiledPath) {
                loadURL = compiledURL
            } else {
                let tmp = try MLModel.compileModel(at: URL(fileURLWithPath: modelPath))
                // Move from the temp location to a stable path beside the source
                try? FileManager.default.removeItem(at: compiledURL)
                try FileManager.default.moveItem(at: tmp, to: compiledURL)
                loadURL = compiledURL
            }
        } else {
            loadURL = URL(fileURLWithPath: modelPath)
        }

        let config = MLModelConfiguration()
        config.computeUnits = .all
        let created = try MLModel(contentsOf: loadURL, configuration: config)
        model = created
        loadedModelPath = modelPath
        return created
    }

    private func buildFeatureProvider(
        model: MLModel,
        encoded: Encoded,
        image: UIImage?,
        imageSide: Int
    ) throws -> MLDictionaryFeatureProvider {
        let inputNames = Set(model.modelDescription.inputDescriptionsByName.keys)
        // Use actual sequence length so it matches the CoreML model's compiled (1, 512) shape
        let seqLen = encoded.inputIds.count
        let ids = try makeMultiArray(shape: [1, NSNumber(value: seqLen)], data: encoded.inputIds.map(Int32.init))
        let mask = try makeMultiArray(shape: [1, NSNumber(value: seqLen)], data: encoded.attentionMask.map(Int32.init))
        let bbox = try makeMultiArray(shape: [1, NSNumber(value: seqLen), 4], data: encoded.bbox.map(Int32.init))
        let tokenType = try makeMultiArray(shape: [1, NSNumber(value: seqLen)], data: [Int32](repeating: 0, count: seqLen))
        let pixel = try makeMultiArray(shape: [1, 3, imageSide as NSNumber, imageSide as NSNumber], data: imageTensor(from: image, side: imageSide))

        var features: [String: MLFeatureValue] = [:]
        if inputNames.contains("input_ids") { features["input_ids"] = MLFeatureValue(multiArray: ids) }
        if inputNames.contains("attention_mask") { features["attention_mask"] = MLFeatureValue(multiArray: mask) }
        if inputNames.contains("bbox") { features["bbox"] = MLFeatureValue(multiArray: bbox) }
        if inputNames.contains("token_type_ids") { features["token_type_ids"] = MLFeatureValue(multiArray: tokenType) }
        if inputNames.contains("pixel_values") { features["pixel_values"] = MLFeatureValue(multiArray: pixel) }

        return try MLDictionaryFeatureProvider(dictionary: features)
    }

    private func makeMultiArray(shape: [NSNumber], data: [Int32]) throws -> MLMultiArray {
        let array = try MLMultiArray(shape: shape, dataType: .int32)
        for (index, value) in data.enumerated() {
            array[index] = NSNumber(value: value)
        }
        return array
    }

    private func makeMultiArray(shape: [NSNumber], data: [Float]) throws -> MLMultiArray {
        let array = try MLMultiArray(shape: shape, dataType: .float32)
        for (index, value) in data.enumerated() {
            array[index] = NSNumber(value: value)
        }
        return array
    }

    private func readLogits(from output: MLFeatureProvider) throws -> [[[Float]]] {
        let logitsFeature = output.featureNames.first { name in
            name.lowercased().contains("logits")
        } ?? output.featureNames.first

        guard let key = logitsFeature,
              let multi = output.featureValue(for: key)?.multiArrayValue else {
            throw NSError(domain: "LayoutLMv3", code: 3, userInfo: [NSLocalizedDescriptionKey: "Model output does not include logits tensor"])
        }

        let shape = multi.shape.map { Int(truncating: $0) }
        guard shape.count == 3 else {
            throw NSError(domain: "LayoutLMv3", code: 4, userInfo: [NSLocalizedDescriptionKey: "Model output must be rank-3 logits [1, seq, labels]"])
        }

        let total = shape.reduce(1, *)
        var arr = Array(repeating: Float(0), count: total)
        for i in 0..<total {
            arr[i] = multi[i].floatValue
        }

        let b = shape[0]
        let s = shape[1]
        let l = shape[2]
        var idx = 0
        var out = Array(repeating: Array(repeating: Array(repeating: Float(0), count: l), count: s), count: b)
        for bi in 0..<b {
            for si in 0..<s {
                for li in 0..<l {
                    out[bi][si][li] = arr[idx]
                    idx += 1
                }
            }
        }
        return out
    }

    // ── BPE vocab types ─────────────────────────────────────────────────────
    private struct MergePair: Hashable {
        let a: String
        let b: String
    }

    private struct BPEVocab {
        let vocab: [String: Int]
        let mergeRanks: [MergePair: Int]
    }

    private struct Encoded {
        let inputIds: [Int64]
        let attentionMask: [Int64]
        let bbox: [Int64]
        let tokens: [String]
    }

    /// Encode OCR text using RoBERTa byte-level BPE tokenisation with
    /// line/word-aware bounding boxes. maxSeqLen should be 512 to match
    /// the CoreML model's compiled fixed shape (1, 512).
    private func encode(text: String, bpeVocab: BPEVocab, maxSeqLen: Int) -> Encoded {
        let rawLines = text.components(separatedBy: "\n")
        let lines: [[String]] = rawLines.map { line in
            line.split(separator: " ").map(String.init).filter { !$0.isEmpty }
        }.filter { !$0.isEmpty }
        let totalLines = max(1, lines.count)

        let bos: Int64 = 0   // <s>
        let eos: Int64 = 2   // </s>

        var tokenIds: [Int64]   = [bos]
        var flatBbox: [Int64]   = [0, 0, 0, 0]
        var tokenStrs: [String] = ["<s>"]

        outerLoop: for (lineIdx, lineWords) in lines.enumerated() {
            let wordsInLine = max(1, lineWords.count)
            let y0 = Int64(lineIdx * 1000 / totalLines)
            let y1 = Int64((lineIdx + 1) * 1000 / totalLines)

            for (wordIdx, word) in lineWords.enumerated() {
                let x0 = Int64(wordIdx * 1000 / wordsInLine)
                let x1 = Int64((wordIdx + 1) * 1000 / wordsInLine)
                let subtokens = bpeTokenize(word: word, isFirstWord: wordIdx == 0, bpeVocab: bpeVocab)
                for subtoken in subtokens {
                    guard tokenIds.count < maxSeqLen - 1 else { break outerLoop }
                    tokenIds.append(Int64(bpeVocab.vocab[subtoken] ?? 3))
                    flatBbox.append(contentsOf: [x0, y0, x1, y1])
                    tokenStrs.append(subtoken)
                }
            }
        }

        if tokenIds.count < maxSeqLen {
            tokenIds.append(eos)
            flatBbox.append(contentsOf: [0, 0, 0, 0])
            tokenStrs.append("</s>")
        }

        let seqLen = tokenIds.count
        var ids  = Array(repeating: Int64(1), count: maxSeqLen)
        var mask = Array(repeating: Int64(0), count: maxSeqLen)
        var bbox = Array(repeating: Int64(0), count: maxSeqLen * 4)

        for i in 0..<seqLen {
            ids[i]          = tokenIds[i]
            mask[i]         = 1
            bbox[i * 4]     = flatBbox[i * 4]
            bbox[i * 4 + 1] = flatBbox[i * 4 + 1]
            bbox[i * 4 + 2] = flatBbox[i * 4 + 2]
            bbox[i * 4 + 3] = flatBbox[i * 4 + 3]
        }

        return Encoded(inputIds: ids, attentionMask: mask, bbox: bbox, tokens: tokenStrs)
    }

    /// Byte-level BPE tokeniser (RoBERTa convention).
    /// Non-first words in a line receive a Ġ (U+0120) space-prefix.
    private func bpeTokenize(word: String, isFirstWord: Bool, bpeVocab: BPEVocab) -> [String] {
        guard !word.isEmpty else { return [] }
        let prefixed = isFirstWord ? word : "Ġ" + word
        if bpeVocab.vocab[prefixed] != nil { return [prefixed] }

        var symbols: [String]
        if isFirstWord {
            symbols = word.map { String($0) }
        } else {
            var chars = word.map { String($0) }
            if !chars.isEmpty { chars[0] = "Ġ" + chars[0] }
            symbols = chars
        }
        guard !symbols.isEmpty else { return [] }

        while symbols.count > 1 {
            var bestRank = Int.max
            var bestIdx  = -1
            for i in 0..<symbols.count - 1 {
                let pair = MergePair(a: symbols[i], b: symbols[i + 1])
                if let rank = bpeVocab.mergeRanks[pair], rank < bestRank {
                    bestRank = rank
                    bestIdx  = i
                }
            }
            guard bestIdx >= 0 else { break }
            symbols[bestIdx] = symbols[bestIdx] + symbols[bestIdx + 1]
            symbols.remove(at: bestIdx + 1)
        }
        return symbols
    }

    private struct Entity {
        let label: String
        let text: String
        let score: Double
    }

    private func decodeEntities(logits: [[[Float]]], tokens: [String], labels: [Int: String]) -> [Entity] {
        guard let seq = logits.first else { return [] }
        let limit = min(seq.count, tokens.count)
        var entities: [Entity] = []

        for i in 0..<limit {
            let probs = softmax(seq[i])
            guard let best = probs.enumerated().max(by: { $0.element < $1.element }) else { continue }
            let labelRaw = labels[best.offset] ?? "O"
            // Skip RoBERTa special tokens (<s>, </s>, <pad>) and Outside label
            if labelRaw == "O" || tokens[i] == "<s>" || tokens[i] == "</s>" || tokens[i] == "<pad>" { continue }
            if Double(best.element) < minimumTokenConfidence { continue }
            let label = labelRaw.replacingOccurrences(of: "B-", with: "").replacingOccurrences(of: "I-", with: "")
            let cleaned = sanitizeEntityToken(tokens[i])
            if cleaned.isEmpty { continue }
            entities.append(Entity(label: label, text: cleaned, score: Double(best.element)))
        }

        return mergeEntities(entities)
    }

    private func mergeEntities(_ entities: [Entity]) -> [Entity] {
        guard var current = entities.first else { return [] }
        var merged: [Entity] = []
        for e in entities.dropFirst() {
            if e.label == current.label {
                current = Entity(label: current.label, text: "\(current.text) \(e.text)", score: max(current.score, e.score))
            } else {
                merged.append(current)
                current = e
            }
        }
        merged.append(current)
        return merged
    }

    private func entitiesToFields(_ entities: [Entity]) -> [String: Any] {
        var fields: [String: Any] = [:]

        // --- line item accumulation ---
        var lineItems: [[String: Any]] = []
        var currentItem: [String: Any] = [:]

        func flushItem() {
            guard !currentItem.isEmpty,
                  currentItem["description"] != nil || currentItem["unit_price"] != nil else { return }
            lineItems.append(currentItem)
            currentItem = [:]
        }

        func setField(_ key: String, _ value: Any) {
            if fields[key] == nil { fields[key] = value }
        }

        for e in entities {
            let label = e.label.uppercased()

            // ── Identifiers ──────────────────────────────────────────────────
            if label == "INVOICE_NUMBER" {
                if let v = normalizeIdentifier(e.text) { setField("invoice_number", v) }
            } else if label == "RECEIPT_NUMBER" {
                if let v = normalizeIdentifier(e.text) { setField("receipt_number", v) }
            } else if label == "ORDER_NUMBER" {
                if let v = normalizeIdentifier(e.text) { setField("order_number", v) }
            } else if label == "PO_NUMBER" {
                if let v = normalizeIdentifier(e.text) { setField("po_number", v) }

            // ── Dates ────────────────────────────────────────────────────────
            } else if label == "DATE" {
                if let v = normalizeDate(e.text) { setField("date_issued", v) }
            } else if label == "DUE_DATE" {
                if let v = normalizeDate(e.text) { setField("due_date", v) }

            // ── Vendor ───────────────────────────────────────────────────────
            } else if label == "VENDOR_NAME" {
                if let v = normalizeVendorName(e.text) { setField("vendor_name", v) }
            } else if label == "VENDOR_ADDRESS" {
                let v = e.text.trimmingCharacters(in: .whitespacesAndNewlines)
                if v.count >= 5 { setField("vendor_address", v) }

            // ── Buyer ────────────────────────────────────────────────────────
            } else if label == "BUYER_NAME" {
                if let v = normalizeVendorName(e.text) { setField("buyer_name", v) }
            } else if label == "BUYER_ADDRESS" {
                let v = e.text.trimmingCharacters(in: .whitespacesAndNewlines)
                if v.count >= 5 { setField("buyer_address", v) }

            // ── Totals ───────────────────────────────────────────────────────
            } else if label == "GRAND_TOTAL" {
                if let amt = parseAmount(e.text) { setField("grand_total", amt) }
            } else if label == "SUBTOTAL" {
                if let amt = parseAmount(e.text) { setField("sub_total", amt) }
            } else if label == "TOTAL_TAX" {
                if let amt = parseAmount(e.text) { setField("total_tax", amt) }
            } else if label == "AMOUNT_DUE" {
                if let amt = parseAmount(e.text) { setField("amount_due", amt) }

            // ── Payment ──────────────────────────────────────────────────────
            } else if label == "PAYMENT_METHOD" {
                let v = e.text.trimmingCharacters(in: .whitespacesAndNewlines)
                if v.count >= 2 { setField("payment_method", v) }

            // ── Line items ───────────────────────────────────────────────────
            } else if label == "ITEM_DESCRIPTION" {
                flushItem()
                currentItem["description"] = e.text.trimmingCharacters(in: .whitespacesAndNewlines)
            } else if label == "ITEM_QUANTITY" {
                let raw = e.text.replacingOccurrences(of: "[^0-9.]", with: "", options: .regularExpression)
                if let qty = Double(raw) { currentItem["quantity"] = qty }
            } else if label == "ITEM_UNIT_PRICE" {
                if let price = parseAmount(e.text) { currentItem["unit_price"] = price }
            } else if label == "ITEM_TOTAL" {
                if let total = parseAmount(e.text) { currentItem["total"] = total }
            }
        }

        flushItem()
        if !lineItems.isEmpty { fields["line_items"] = lineItems }

        return fields
    }

    private func parseAmount(_ raw: String) -> Double? {
        let cleaned = raw.replacingOccurrences(of: "[^0-9.-]", with: "", options: .regularExpression)
        guard let value = Double(cleaned), value > 0, value <= 10_000_000 else {
            return nil
        }
        return value
    }

    private func normalizeIdentifier(_ raw: String) -> String? {
        let cleaned = raw.uppercased().replacingOccurrences(of: "[^A-Z0-9\\-/]", with: "", options: .regularExpression)
        guard cleaned.count >= 2, cleaned.count <= 40 else { return nil }
        guard cleaned.contains(where: { $0.isNumber }) else { return nil }
        return cleaned
    }

    private func normalizeDate(_ raw: String) -> String? {
        guard let rx = try? NSRegularExpression(pattern: "(\\d{1,4}[/-]\\d{1,2}[/-]\\d{1,4})") else {
            return nil
        }
        let ns = raw as NSString
        guard let match = rx.firstMatch(in: raw, range: NSRange(location: 0, length: ns.length)) else {
            return nil
        }
        return ns.substring(with: match.range(at: 1))
    }

    private func normalizeVendorName(_ raw: String) -> String? {
        let cleaned = raw.replacingOccurrences(of: "[^A-Za-z0-9 &.,'-]", with: " ", options: .regularExpression)
            .replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard cleaned.count >= 3 else { return nil }
        let letters = cleaned.filter { $0.isLetter }.count
        guard letters >= 3 else { return nil }
        return cleaned
    }

    private func sanitizeEntityToken(_ raw: String) -> String {
        return raw.replacingOccurrences(of: "[^A-Za-z0-9$.,:/#&()\\-]", with: "", options: .regularExpression)
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// Returns true if `labels` is a valid BIO token-classification label map:
    /// must have at least an Outside ("O") label and one or more B- prefixed entities.
    /// Domain-specific keywords are NOT required — any BIO labeled file is accepted.
    private func isValidLabelMap(_ labels: [Int: String]) -> Bool {
        guard !labels.isEmpty else { return false }
        let normalized = labels.values.map { $0.uppercased() }
        let hasOutside = normalized.contains("O")
        let hasBioLabel = normalized.contains(where: { $0.hasPrefix("B-") || $0.hasPrefix("I-") })
        return hasOutside && hasBioLabel
    }

    // Keep for compatibility — callers that want a throwing variant can use this.
    private func validateLabelMap(_ labels: [Int: String]) throws {
        guard isValidLabelMap(labels) else {
            throw NSError(
                domain: "LayoutLMv3",
                code: 21,
                userInfo: [
                    NSLocalizedDescriptionKey: "LayoutLMv3 labels file appears incompatible. Provide token-classification labels with O/B-/I- tags for invoice entities."
                ]
            )
        }
    }

    private func imageTensor(from image: UIImage?, side: Int) -> [Float] {
        let count = 3 * side * side
        guard let image else { return Array(repeating: 0, count: count) }
        UIGraphicsBeginImageContextWithOptions(CGSize(width: side, height: side), true, 1)
        image.draw(in: CGRect(x: 0, y: 0, width: side, height: side))
        guard let scaled = UIGraphicsGetImageFromCurrentImageContext(),
              let cg = scaled.cgImage,
              let provider = cg.dataProvider,
              let raw = provider.data else {
            UIGraphicsEndImageContext()
            return Array(repeating: 0, count: count)
        }
        UIGraphicsEndImageContext()

        let ptr = CFDataGetBytePtr(raw)
        let bytesPerPixel = 4
        var out = Array(repeating: Float(0), count: count)
        let mean: [Float] = [0.485, 0.456, 0.406]
        let std: [Float] = [0.229, 0.224, 0.225]

        var rIdx = 0
        var gIdx = side * side
        var bIdx = 2 * side * side

        for y in 0..<side {
            for x in 0..<side {
                let offset = (y * side + x) * bytesPerPixel
                let r = Float(ptr?[offset] ?? 0) / 255.0
                let g = Float(ptr?[offset + 1] ?? 0) / 255.0
                let b = Float(ptr?[offset + 2] ?? 0) / 255.0

                out[rIdx] = (r - mean[0]) / std[0]
                out[gIdx] = (g - mean[1]) / std[1]
                out[bIdx] = (b - mean[2]) / std[2]
                rIdx += 1
                gIdx += 1
                bIdx += 1
            }
        }

        return out
    }

    private func loadLabels(labelsPath: String?) -> [Int: String] {
        guard let labelsPath,
              FileManager.default.fileExists(atPath: labelsPath),
              let data = try? Data(contentsOf: URL(fileURLWithPath: labelsPath)) else {
            return defaultLabels()
        }

        // 1a. Try {"0": "O", "1": "B-INVOICE_NUMBER", ...} — standard DataLift format
        if let dict = try? JSONSerialization.jsonObject(with: data) as? [String: String] {
            var out: [Int: String] = [:]
            for (k, v) in dict {
                if let id = Int(k) { out[id] = v }
            }
            if !out.isEmpty { return out }
        }

        // 1b. Try {"id2label": {"0": "O", ...}, ...} — HuggingFace config.json wrapper
        if let top = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
           let inner = top["id2label"] as? [String: String] {
            var out: [Int: String] = [:]
            for (k, v) in inner {
                if let id = Int(k) { out[id] = v }
            }
            if !out.isEmpty { return out }
        }

        // 2. Try plain JSON array format: ["O", "B-INVOICE_NUMBER", ...]
        if let arr = try? JSONSerialization.jsonObject(with: data) as? [String] {
            return Dictionary(uniqueKeysWithValues: arr.enumerated().map { ($0.offset, $0.element) })
        }

        if let text = String(data: data, encoding: .utf8) {
            let lines = text.split(separator: "\n").map { String($0).trimmingCharacters(in: .whitespacesAndNewlines) }.filter { !$0.isEmpty }
            if !lines.isEmpty {
                return Dictionary(uniqueKeysWithValues: lines.enumerated().map { ($0.offset, $0.element) })
            }
        }

        return defaultLabels()
    }

    /// Load RoBERTa BPE vocabulary (vocab.json) and merge rules (merges.txt)
    /// from the model directory. Returns a BPEVocab ready for tokenisation.
    private func loadVocab(modelPath: String) -> BPEVocab {
        let modelDir = URL(fileURLWithPath: modelPath).deletingLastPathComponent()
        var vocab: [String: Int] = [:]
        var mergeRanks: [MergePair: Int] = [:]

        // Load vocab.json — RoBERTa BPE format: {"Ġthe": 262, ...}
        let vocabURL = modelDir.appendingPathComponent("vocab.json")
        if let data = try? Data(contentsOf: vocabURL),
           let dict = try? JSONSerialization.jsonObject(with: data) as? [String: Int] {
            vocab = dict
        }

        // Load merges.txt — one merge pair per line, priority = line index
        let mergesURL = modelDir.appendingPathComponent("merges.txt")
        if let text = try? String(contentsOf: mergesURL, encoding: .utf8) {
            var rank = 0
            for line in text.split(separator: "\n") {
                let t = String(line).trimmingCharacters(in: .whitespaces)
                if t.hasPrefix("#") || t.isEmpty { continue }
                let parts = t.split(separator: " ", maxSplits: 1).map(String.init)
                if parts.count == 2 {
                    mergeRanks[MergePair(a: parts[0], b: parts[1])] = rank
                    rank += 1
                }
            }
        }

        return BPEVocab(vocab: vocab, mergeRanks: mergeRanks)
    }

    private func softmax(_ values: [Float]) -> [Float] {
        guard let maxVal = values.max() else { return [] }
        let exps = values.map { Foundation.exp(Double($0 - maxVal)) }
        let sum = exps.reduce(0, +)
        guard sum > 0 else { return Array(repeating: 0, count: values.count) }
        return exps.map { Float($0 / sum) }
    }

    // ::: Code Generated by Copilot a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d. This comment will be removed automatically after the file is saved :::
    /// Default label map matching the fine-tuned LayoutLMv3 model in datalift-models/labels.json.
    private func defaultLabels() -> [Int: String] {
        return [
            0: "O",
            1: "B-INVOICE_NUMBER",
            2: "I-INVOICE_NUMBER",
            3: "B-RECEIPT_NUMBER",
            4: "I-RECEIPT_NUMBER",
            5: "B-DATE",
            6: "I-DATE",
            7: "B-DUE_DATE",
            8: "I-DUE_DATE",
            9: "B-VENDOR_NAME",
            10: "I-VENDOR_NAME",
            11: "B-VENDOR_ADDRESS",
            12: "I-VENDOR_ADDRESS",
            13: "B-BUYER_NAME",
            14: "I-BUYER_NAME",
            15: "B-BUYER_ADDRESS",
            16: "I-BUYER_ADDRESS",
            17: "B-PO_NUMBER",
            18: "I-PO_NUMBER",
            19: "B-ORDER_NUMBER",
            20: "I-ORDER_NUMBER",
            21: "B-GRAND_TOTAL",
            22: "I-GRAND_TOTAL",
            23: "B-SUBTOTAL",
            24: "I-SUBTOTAL",
            25: "B-TOTAL_TAX",
            26: "I-TOTAL_TAX",
            27: "B-AMOUNT_DUE",
            28: "I-AMOUNT_DUE",
            29: "B-ITEM_DESCRIPTION",
            30: "I-ITEM_DESCRIPTION",
            31: "B-ITEM_QUANTITY",
            32: "I-ITEM_QUANTITY",
            33: "B-ITEM_UNIT_PRICE",
            34: "I-ITEM_UNIT_PRICE",
            35: "B-ITEM_TOTAL",
            36: "I-ITEM_TOTAL",
            37: "B-PAYMENT_METHOD",
            38: "I-PAYMENT_METHOD",
        ]
    }

}

private extension Data {
    init<T>(from array: [T]) {
        self = array.withUnsafeBufferPointer { Data(buffer: $0) }
    }
}
