// ::: Code Generated by Copilot d4e5f6a7-b8c9-4d0e-a1f2-3b4c5d6e7f80. This comment will be removed automatically after the file is saved :::
/**
 * DataLift – ModelManager
 *
 * Handles the full lifecycle of the on-device LayoutLMv3 model:
 *   1. Checks for bundled model files shipped with the package (datalift-models/)
 *   2. Checks if the model is already present in app storage
 *   3. Falls back to remote download from GitHub Releases when configured
 *   4. Returns resolved { modelPath, labelsPath } ready for configureLayoutLMv3()
 *
 * The fine-tuned model files are in datalift-models/:
 *   - labels.json                          (39-label BIO token classification)
 *   - vocab.json                           (RoBERTa BPE vocabulary)
 *   - layoutlmv3-base-doc-android.onnx     (Android ONNX model)
 *   - onnx/model.onnx + model.onnx.data    (Full precision ONNX model)
 *
 * iOS  uses a CoreML compiled model  (.mlpackage / .mlmodelc)
 * Android uses the ONNX Runtime model (.onnx)
 */

import { Platform } from "react-native";
import { DataLift as NativeDataLift } from "../NativeDataLift";

// ─── Bundled model filenames (from datalift-models/) ──────────────────────────

// ::: Code Generated by Copilot d4e5f6a7-b8c9-4d0e-a1f2-3b4c5d6e7f80. This comment will be removed automatically after the file is saved :::
/**
 * Filenames of the fine-tuned model assets bundled in datalift-models/.
 * These are resolved by the native layer from the app bundle (iOS) or
 * assets directory (Android).
 */
const BUNDLED_MODEL_NAMES = {
  android: {
    model: "layoutlmv3-base-doc-android.onnx",
    labels: "labels.json",
    vocab: "vocab.json",
  },
  ios: {
    model: "layoutlmv3-base-doc-android.onnx",
    labels: "labels.json",
    vocab: "vocab.json",
  },
} as const;

// ─── Remote download fallback ─────────────────────────────────────────────────

/** The model asset release tag on GitHub Releases (fallback for remote download). */
export const MODEL_ASSET_TAG = "models-v1";

const RELEASE_BASE = `https://github.com/kajeevan025/datalift-model-training/releases/download/${MODEL_ASSET_TAG}`;

// ::: Code Generated by Copilot d4e5f6a7-b8c9-4d0e-a1f2-3b4c5d6e7f80. This comment will be removed automatically after the file is saved :::
/**
 * Remote URLs used as a fallback when models are not bundled with the app.
 * Only used when autoDownload is enabled and no local model is found.
 */
export const MODEL_URLS = {
  ios: {
    model: `${RELEASE_BASE}/layoutlmv3-base-doc-coreml.mlpackage.zip`,
    labels: `${RELEASE_BASE}/labels.json`,
    vocab: `${RELEASE_BASE}/vocab.json`,
  },
  android: {
    model: `${RELEASE_BASE}/layoutlmv3-base-doc-android.onnx`,
    labels: `${RELEASE_BASE}/labels.json`,
    vocab: `${RELEASE_BASE}/vocab.json`,
  },
} as const;

/** Local filenames when downloading to storage directory */
const DOWNLOAD_FILE_NAMES = {
  ios: {
    model: "layoutlmv3-base-doc-coreml.mlpackage.zip",
    labels: "labels.json",
    vocab: "vocab.json",
  },
  android: {
    model: "layoutlmv3-base-doc-android.onnx",
    labels: "labels.json",
    vocab: "vocab.json",
  },
} as const;

// ─── Public types ─────────────────────────────────────────────────────────────

export interface ModelPaths {
  /** Absolute path to the model file (CoreML .mlpackage on iOS, .onnx on Android) */
  modelPath: string;
  /** Absolute path to the labels.json file */
  labelsPath?: string;
  /** How the model was found – "bundle" (shipped in app), "storage" (already present), "downloaded" (just fetched) */
  source: "bundle" | "storage" | "downloaded";
}

export interface ModelDownloadProgress {
  /** Which file is currently downloading */
  fileName: string;
  /** Bytes received so far */
  bytesReceived: number;
  /** Total file size in bytes (−1 if unknown) */
  totalBytes: number;
  /** Fraction complete, 0–1 */
  progress: number;
}

export type ModelDownloadProgressCallback = (p: ModelDownloadProgress) => void;

export interface EnsureModelOptions {
  /**
   * When true, files are automatically downloaded to local storage
   * if they are not bundled with the app.
   * @default false
   */
  autoDownload?: boolean;

  /**
   * Optional progress callback. Called multiple times during download.
   */
  onProgress?: ModelDownloadProgressCallback;

  /**
   * Override the remote URLs used for downloading.
   * Useful for air-gapped environments or private model servers.
   */
  modelUrls?: Partial<{
    model: string;
    labels: string;
    vocab: string;
  }>;
}

// ─── ModelManager ─────────────────────────────────────────────────────────────

// ::: Code Generated by Copilot d4e5f6a7-b8c9-4d0e-a1f2-3b4c5d6e7f80. This comment will be removed automatically after the file is saved :::
export class ModelManager {
  private _storageDir: string | null = null;

  /**
   * Returns (and caches) the platform storage directory for model files.
   * The directory is created by the native layer if it does not exist.
   */
  async getStorageDir(): Promise<string> {
    if (this._storageDir) return this._storageDir;
    const result = await NativeDataLift.getModelStorageDir();
    this._storageDir = result.path;
    return this._storageDir;
  }

  /**
   * Attempts to find the fine-tuned model files bundled with the app.
   * On Android, the native layer checks assets/ and filesDir.
   * On iOS, the native layer checks Bundle.main resources.
   *
   * The bundled model filenames match those in datalift-models/.
   */
  async getBundledModelPaths(): Promise<ModelPaths | null> {
    try {
      const platform = Platform.OS === "ios" ? "ios" : "android";
      const names = BUNDLED_MODEL_NAMES[platform];

      // The native configureLayoutLMv3 resolves bare filenames from the
      // app bundle (iOS) or assets directory (Android).
      const probe = await NativeDataLift.checkLayoutLMv3Compatibility({
        model_path: names.model,
        labels_path: names.labels,
      });

      if (!probe.checks.model_file) return null;

      return {
        modelPath: probe.model_path ?? names.model,
        labelsPath: probe.checks.labels_file
          ? (probe.labels_path ?? names.labels)
          : undefined,
        source: "bundle",
      };
    } catch {
      return null;
    }
  }

  /**
   * Scans the platform storage directory for already-downloaded model files.
   * Returns `null` when no model is found there.
   */
  async getStoredModelPaths(): Promise<ModelPaths | null> {
    try {
      const dir = await this.getStorageDir();
      const platform = Platform.OS === "ios" ? "ios" : "android";
      const names = DOWNLOAD_FILE_NAMES[platform];

      const modelPath = `${dir}/${names.model}`;
      const labelsPath = `${dir}/${names.labels}`;

      const probe = await NativeDataLift.checkLayoutLMv3Compatibility({
        model_path: modelPath,
        labels_path: labelsPath,
      });

      if (!probe.checks.model_file) return null;

      return {
        modelPath: probe.model_path ?? modelPath,
        labelsPath: probe.checks.labels_file
          ? (probe.labels_path ?? labelsPath)
          : undefined,
        source: "storage",
      };
    } catch {
      return null;
    }
  }

  /**
   * Downloads model files to the platform storage directory.
   * Used as a fallback when models are not bundled with the app.
   *
   * @throws when the native download fails (network error, disk full, etc.)
   */
  async downloadModel(
    onProgress?: ModelDownloadProgressCallback,
    customUrls?: EnsureModelOptions["modelUrls"],
  ): Promise<ModelPaths> {
    const dir = await this.getStorageDir();
    const platform = Platform.OS === "ios" ? "ios" : "android";
    const urls = { ...MODEL_URLS[platform], ...customUrls };
    const names = DOWNLOAD_FILE_NAMES[platform];

    const download = async (
      url: string,
      fileName: string,
      isBig = false,
    ): Promise<string> => {
      const destination = `${dir}/${fileName}`;

      if (onProgress) {
        onProgress({
          fileName,
          bytesReceived: 0,
          totalBytes: isBig ? -1 : 0,
          progress: 0,
        });
      }

      const result = await NativeDataLift.downloadModelFile({
        url,
        destination,
      });

      if (onProgress) {
        onProgress({
          fileName,
          bytesReceived: result.bytes,
          totalBytes: result.bytes,
          progress: 1,
        });
      }

      return result.path;
    };

    // Order: labels → vocab → model (small files first; model last)
    const labelsPath = await download(urls.labels, names.labels);
    await download(urls.vocab, names.vocab);
    const modelPath = await download(urls.model, names.model, true);

    return { modelPath, labelsPath, source: "downloaded" };
  }

  /**
   * High-level entry point.
   *
   * Resolution order:
   *   1. Bundled models (shipped in datalift-models/ and included in the app)
   *   2. Previously downloaded models in device storage
   *   3. Remote download (if autoDownload is true)
   *   4. null (model unavailable – caller should skip LayoutLMv3)
   */
  async ensureModel(
    options: EnsureModelOptions = {},
  ): Promise<ModelPaths | null> {
    // 1. Check for bundled models first
    const bundled = await this.getBundledModelPaths();
    if (bundled) return bundled;

    // 2. Already in storage?
    const stored = await this.getStoredModelPaths();
    if (stored) return stored;

    // 3. Download if allowed
    if (!options.autoDownload) return null;

    return this.downloadModel(options.onProgress, options.modelUrls);
  }
}

/** Singleton instance — reused across calls to avoid repeated directory probes. */
export const defaultModelManager = new ModelManager();
